OpenZeppelin/openzeppelin-sdk

packages/lib/changelog.md
packages/lib/src/utils/Transactions.js

Fixes https://github.com/zeppelinos/zos/issues/23.

Promisify web3 node version function

---

packages/cli/src/utils/runWithTruffle.js

Fixes https://github.com/zeppelinos/zos/issues/20

Fix not exiting terminal when using HDWalletProvider

---

.gitignore
package-lock.json

Fixes https://github.com/zeppelinos/zos/issues/45

Ignore node_modules and add package-lock file for root dir

---

packages/cli/src/commands/index.js
packages/cli/src/commands/unlink.js
packages/cli/src/models/local/LocalAppController.js
packages/cli/src/models/network/NetworkAppController.js
packages/cli/src/scripts/unlink.js
packages/cli/test/commands/share.js
packages/cli/test/commands/unlink.test.js
packages/cli/test/mocks/packages/package-with-multiple-stdlibs.zos.json
packages/cli/test/scripts/unlink.test.js

Implemented a new cli command for unlinking a list of multiple dependencies. 
_Example usage:_
```console
foo@bar:~$ zos unlink openzeppelin-zos gnosis-safe
```

Add CLI command to remove dependencies

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/models/truffle/Truffle.js
packages/cli/src/utils/runWithTruffle.js

Fixes https://github.com/zeppelinos/zos/issues/55
- Injecting nonce subprovider manually when using Web3ProviderEngine
- Adding provider object inside artifacts options object

Inject nonce subprovider if necessary

---

design/lightweight-upgradeability-functions.md

Design document for lightweight upgradeability functions

---

packages/docs/docs/docs/writing_contracts.md

Add clarification on adding storage vars to base contracts

---

packages/docs/docs/docs/writing_contracts.md

To warn against https://github.com/zeppelinos/zos/issues/60

Add clarification to avoid initial values on field declarations

---

packages/lib/test/contracts/application/ImplementationDirectory.test.js
packages/lib/test/contracts/application/Package.test.js

Just removing an old dir left after refactoring the lib contracts architecture

Remove old application/versioning test dir

---

packages/cli/package-lock.json
packages/lib/package-lock.json
packages/vouching/package-lock.json

Output of running `npx lerna bootstrap`

Update package locks

---

packages/cli/src/bin/program.js
packages/cli/src/index.js
packages/cli/src/models/local/index.js
packages/cli/src/models/network/index.js
packages/cli/src/scripts/index.js

Fixes #40 
I exported both scripts and commands

Export commands and scripts

---

packages/vouching/package.json

Making vouching project public to publish it on NPM

Make vouching public

---

packages/vouching/.gitignore
packages/vouching/contracts/ZEPValidator.sol
packages/vouching/package-lock.json
packages/vouching/package.json
packages/vouching/truffle-config.js
packages/vouching/zos.json
packages/vouching/zos.ropsten.json

This PR addresses issue #154 **"Setup kernel ZeppelinOS app project"**

Initialize vouching as a zOS app

---

packages/vouching/contracts/Vouching.sol

Fixes `Vouching` contract warnings

Use abi.encodePacked for Vouching contract

---

packages/cli/src/models/local/LocalBaseController.js
packages/lib/contracts/mocks/GetFunctionMocks.sol
packages/lib/src/index.js
packages/lib/src/utils/ABIs.js
packages/lib/src/utils/ContractAST.js
packages/lib/test/src/utils/ABIs.test.js
tests/cli-app/dependencies/mock-stdlib-1.1.0/build/contracts/Greeter.json
tests/cli-app/dependencies/mock-stdlib-1.1.0/build/contracts/Parent.json
tests/cli-app/dependencies/mock-stdlib-1.1.0/contracts/Parent.sol
tests/cli-app/dependencies/mock-stdlib-1.2.0/build/contracts/Greeter.json
tests/cli-app/dependencies/mock-stdlib-1.2.0/build/contracts/Parent.json
tests/cli-app/dependencies/mock-stdlib-1.2.0/contracts/Parent.sol
tests/cli-app/files/Samples.sol
tests/cli-app/files/SamplesV2.sol

Improve ABI parsing for initialization

---

packages/lib/src/utils/Contracts.js
packages/lib/src/utils/Transactions.js
packages/lib/test/src/utils/Transactions.test.js
tests/cli-app/workdir/truffle.js

Mitigation until #56 is implemented.

Refuse to run transactions with truffle default gas price

---

packages/cli/src/utils/runWithTruffle.js

Fixes https://github.com/zeppelinos/zos/issues/180

Throw error if provided network is not defined

---

packages/lib/contracts/application/App.sol

Fixes issues [zOS2L-O04] of the Nomic audit (part of #205).

Newly created proxy addresses are no longer indexed in the event.

---

packages/vouching/test/contracts/Vouching.test.js

Fixes issue [zOS2V-O04] of the Nomic audit (part of #203).
Note that this sort of thing wouldn't have been caught by `solidity-coverage`, we need better tooling :/

Fixed wrong unvouching test.

---

packages/vouching/contracts/ZEPToken.sol
packages/vouching/test/contracts/ZEPToken.test.js

Fixes issues [zOS2V-O01] & [zOS2V-O02] of the Nomic audit (part of #203).

Improved ZEP-TPL interaction documentation and tests

---

packages/cli/src/interface/ValidationLogger.js
packages/cli/test/interface/ValidationLogger.test.js
packages/lib/contracts/mocks/WithInitialValues.sol
packages/lib/src/validations/InitialValues.js
packages/lib/src/validations/index.js
packages/lib/test/src/validations/Validations.test.js

Fixes https://github.com/zeppelinos/zos/issues/80.

Detect initial values in fields declarations

---

packages/cli/src/commands/init.js
packages/cli/src/models/network/NetworkAppController.js
packages/cli/src/models/network/NetworkBaseController.js
packages/cli/test/commands/init.test.js
packages/cli/test/scripts/freeze.test.js
packages/cli/test/scripts/push.test.js

Drop libs distinction on init

---

packages/lib/src/validations/index.js
packages/lib/test/src/validations/Validations.test.js

Temporarily remove validation of uninit base contracts

---

packages/cli/src/interface/ValidationLogger.js
packages/docs/docs/docs/advanced.md

Added 'Safety checks' section to docs and linked to it from add command.

---

packages/docs/docs/website/siteConfig.js

docs: add algolia search

---

packages/docs/docs/website/static/css/custom.css

docs: remove and extra } and fixed spacing on css

---

packages/cli/src/models/network/NetworkAppController.js
packages/cli/test/scripts/push.test.js

Update dependencies version on push

---

packages/cli/src/models/files/ZosNetworkFile.js
packages/cli/src/models/network/NetworkBaseController.js
packages/cli/test/scripts/push.test.js

Reupload contract if related lib has changed

---

packages/cli/src/models/network/NetworkBaseController.js
packages/cli/test/scripts/freeze.test.js

Fixes https://github.com/zeppelinos/zos/issues/265.

Check if project is published before freeze

---

packages/cli/src/models/network/NetworkBaseController.js

Updated status fix/fetch error message for ~lightweight~ unpublished projects.

Change status fix/fetch error message

---

packages/cli/package.json
packages/docs/package.json
packages/lib/package.json
packages/vouching/package.json

Fixes https://github.com/zeppelinos/zos/issues/283
I'm using the descriptions proposed by @elopio in https://github.com/zeppelinos/zos/issues/232 to update the package.json files of the different sub-repos

Update and unify package json files structures

---

packages/docs/docs/docs/writing_contracts.md

docs: fix typo

---

packages/docs/docs/docs/writing_contracts.md

docs: update writing contracts to openzeppelin-eth

---

packages/docs/docs/docs/architecture.md

docs: update references to openzeppelin-eth in architecture

---

packages/docs/docs/docs/proxies.md

docs: fix formatting of the proxy pattern diagram

---

packages/docs/docs/docs/new_2.x

docs: fix titles on what's new on 2.x

---

packages/docs/docs/website/core/Footer.js
packages/docs/docs/website/static/css/custom.css

docs: add a link to report bugs in the footer

---

packages/docs/docs/docs/architecture.md
packages/docs/docs/docs/deploying.md
packages/docs/docs/docs/erc20_onboarding.md
packages/docs/docs/docs/linking.md
packages/docs/docs/docs/mainnet.md
packages/docs/docs/docs/pattern.md
packages/docs/docs/docs/publish.md
packages/docs/docs/docs/testing.md
packages/docs/docs/docs/upgradeability_governance.md
packages/docs/docs/docs/upgrading.md
packages/docs/docs/docs/writing_contracts.md
packages/docs/docs/docs/zos_lib.md

This removes the weird bold words that appeared on some blocks
[CI skip]

docs: fix the code blocks

---

packages/docs/docs/docs/deploying.md
packages/docs/docs/docs/linking.md
packages/docs/docs/docs/upgrading.md

docs: remove the NODE_ENV workaround

---

packages/docs/scripts/bump-docs.js
packages/docs/scripts/generators.js
packages/vouching/contracts/Vouching.sol
packages/vouching/contracts/ZEPToken.sol
packages/vouching/package.json

NOTE: This PR is a cleaner version of https://github.com/zeppelinos/zos/pull/300 in terms of commit history and changes.
Fixes #147

Adds natspec documentation to the vouching package (CLEANER VERSION)

---

packages/docs/docs/docs/deploying.md

Fix https://github.com/zeppelinos/zos/issues/19

Added a bit more details for the push command.

---

packages/docs/docs/docs/configuration.md

Fix https://github.com/zeppelinos/zos/issues/6

Added comments about zos json files in vcs.

---

packages/vouching/README.md

docs: add the vouching README

---

packages/docs/docs/website/siteConfig.js
packages/docs/docs/website/static/css/custom.css

Fixes Fixed some bugs regarding css styling. This PR includes:
- Fixes in navbar image logo and version link position for both mobile and desktop
- Fixes in titles and sidebar sections overflows
- Some minor changes in font sizes and margins for paragrahps, titles and subtitles.

Fix in docs styles

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/models/network/NetworkAppController.js
packages/cli/test/mocks/mock-stdlib-unpublished/build/contracts/GreeterBase.json
packages/cli/test/mocks/mock-stdlib-unpublished/build/contracts/GreeterImpl.json
packages/cli/test/mocks/mock-stdlib-unpublished/contracts/GreeterBase.sol
packages/cli/test/mocks/mock-stdlib-unpublished/contracts/GreeterImpl.sol
packages/cli/test/mocks/mock-stdlib-unpublished/package.json
packages/cli/test/mocks/mock-stdlib-unpublished/truffle.js
packages/cli/test/mocks/mock-stdlib-unpublished/zos.json
packages/cli/test/mocks/mock-stdlib-unpublished/zos.test.json
packages/cli/test/mocks/packages/package-with-unpublished-stdlib.zos.json
packages/cli/test/scripts/push.test.js
packages/lib/src/project/SimpleProject.js

Throw error if a dependency was unpublished when trying to link it

---

packages/lib/src/utils/Transactions.js
packages/lib/test/src/utils/Transactions.test.js

Also rephrased error message, and added link to ethgasstation for
obtaining a reasonable value.
Fixes #328

Do not check gas price if working on ganache

---

packages/docs/docs/docs/linking.md

docs: add a link to the difference between openzeppelin-solidity and openzeppelin-eth

---

packages/docs/docs/docs/erc20_onboarding.md

docs: remove spurious character

---

packages/docs/docs/docs/new_2.md
packages/docs/docs/docs/writing_contracts.md

docs: fix link to constructor caveat

---

packages/docs/docs/docs/architecture.md

docs: fix link to diagram

---

packages/docs/docs/docs/pattern.md

docs: fix titles in the pattern page

---

packages/docs/docs/docs/deploying.md
packages/docs/docs/docs/upgrading.md

Related to https://github.com/zeppelinos/zos/issues/343

Add create proxy example with multiple args

---

packages/docs/docs/docs/deploying.md

docs: polish the deploying guide

---

packages/docs/docs/docs/deploying.md
packages/docs/docs/docs/erc20_onboarding.md
packages/docs/docs/docs/upgrading.md
packages/docs/docs/docs/zos_lib.md

Related to https://github.com/zeppelinos/zos/issues/343.

Replace `truffle develop` with `truffle console` + ganache

---

packages/docs/docs/docs/configuration.md
packages/docs/docs/docs/new_2.md
packages/docs/docs/docs/pattern.md
packages/docs/docs/docs/publish.md
packages/docs/docs/docs/writing_contracts.md

Correct all spelling mistakes in docs

---

packages/docs/docs/docs/zos_lib.md

Remove all todos from docs

---

packages/docs/docs/docs/pattern.md

Explanation on transparent proxies

---

examples/truffle-migrate/README.md
examples/truffle-migrate/contracts/Migrations.sol
examples/truffle-migrate/contracts/MyContract_v0.sol
examples/truffle-migrate/contracts/MyContract_v1.sol
examples/truffle-migrate/index.js
examples/truffle-migrate/migrations/1_initial_migration.js
examples/truffle-migrate/migrations/2_deploy_v0.js
examples/truffle-migrate/migrations/3_deploy_v1.js
examples/truffle-migrate/package-lock.json
examples/truffle-migrate/package.json
examples/truffle-migrate/truffle.js
examples/truffle-migrate/zos.json

Adds an example of using `zos` CLI scripts js interface from truffle migrations.

Example project with truffle migrations

---

packages/docs/docs/website/versioned_docs/version-2.0.0/zos_lib.md

Line 131 typo on Adnd
https://github.com/zeppelinos/zos/blob/master/packages/docs/docs/website/versioned_docs/version-2.0.0/zos_lib.md

Fixed typo on version-2.0.0/zos_lib.md

---

tests/cli-app/package-lock.json
tests/cli-app/package.json

Integration tests are throwing the following error:
```bash
Error: Cannot find module 'truffle-hdwallet-provider'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/travis/build/zeppelinos/zos/tests/cli-app/workdir/truffle.js:1:88)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/travis/build/zeppelinos/zos/tests/cli-app/test/share.js:5:23)
at Module._compile (module.js:653:30)
at …
```

Add truffle-hdwallet-provider to integration tests

---

design/token-mechanics-v2.1.md
design/token-mechanics-v2.md

Token mechanics challenges + public vouching proposal

---

design/vouching-contracts-v2.1.md

Fixes #471 
Specification for the vouching contracts to be implemented for the upcoming phase. These specs adhere to the rules laid out in #528.

Spec for vouching contracts

---

packages/cli/src/models/compiler/Compiler.ts

Force compiling all contracts

---

packages/docs/docs/docs/deploying.md
packages/docs/docs/docs/linking.md
packages/docs/docs/docs/upgrading.md
packages/docs/docs/docs/zos_lib.md

Docs small fixes

---

packages/docs/docs/website/versioned_docs/version-2.0.0/writing_contracts.md

added missing 'E'

---

.mergify.yml

Update mergify to v2

---

packages/cli/src/models/initializer/ConfigVariablesInitializer.ts
packages/cli/src/models/initializer/truffle/Truffle.ts
packages/cli/src/models/network/Session.ts
packages/lib/src/artifacts/ZWeb3.ts
packages/lib/test/src/artifacts/ZWeb3.test.js

Fixes https://github.com/zeppelinos/zos/issues/648.

Checksum `from` address to avoid addresses comparison fail 

---

packages/docs/docs/docs/erc20_onboarding.md

Updates the erc20 onboarding guide to zOS 2.1.

---

packages/cli/src/commands/verify.ts
packages/docs/docs/docs/deploying.md
packages/docs/docs/docs/writing_contracts.md

Minor fixes for 2.1 documentation

---

packages/docs/docs/docs/faq.md
packages/docs/docs/website/sidebars.json

Fix #566 
Part of #635 
Also adds a faq on how to specify the Solidity compiler version.

Add a new faq section to docs.

---

packages/docs/docs/docs/zos_lib.md

Update the programmatic usage guide in docs for zOS 2.1

---

packages/docs/docs/docs/upgrading.md

Add a note to "upgrading.md" about initializing new variables.

---

examples/cli-with-deps/package-lock.json
packages/cli/package-lock.json
packages/docs/package-lock.json
packages/lib/package-lock.json

Attempt to fix package-lock errors.

Fix package-locks

---

tests/cli-app/test/integration.test.js
tests/cli-app/test/project.js

Attempt to fix integration tests

Fix integration tests

---

packages/cli/changelog.md
packages/lib/changelog.md

Update cli and lib changelogs

---

packages/docs/docs/docs/zepkit.md
packages/docs/docs/website/i18n/en.json
packages/docs/docs/website/sidebars.json

@ajsantander @ajsantander 
Introduces the zepkit. Not sure if we need to create versioned-docs because the instructions are generic and redirect to the website

Creates ZepKit page inside the docs

---

packages/docs/docs/docs/erc20_onboarding.md
packages/docs/docs/docs/zos_lib.md

Minor fixes for 2.1 docs

---

packages/docs/docs/docs/architecture.md
packages/docs/docs/docs/configuration.md
packages/docs/docs/docs/faq.md
packages/docs/docs/docs/new_2.2.md
packages/docs/docs/docs/new_2.md
packages/docs/docs/docs/pattern.md
packages/docs/docs/docs/vouching.md
packages/docs/docs/website/sidebars.json

@ajsantander I'm cherry picking your changes from [docs/2.2](https://github.com/zeppelinos/zos/tree/docs/2.2) branch and merging against `master`. Please review and merge if I didn't miss anything.

Update master with latests docs fixes

---

packages/docs/docs/docs/writing_contracts.md

Replace reference in documentation to BaseApp with App

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/commands/init.ts
packages/cli/src/utils/prompt.ts
packages/cli/test/utils/prompt.test.js
packages/lib/src/utils/FileSystem.ts

Fixes https://github.com/zeppelinos/zos/issues/713.
This PR makes the `init` command interactive, by asking both `project-name` and `version` parameters if not provided, and hinting the `name` and `version` values from the `package.json` file if possible:

Interactive init

---

packages/cli/src/commands/create.ts
packages/cli/src/commands/publish.ts
packages/cli/src/commands/set-admin.ts
packages/cli/src/commands/update.ts
packages/cli/src/models/files/ZosNetworkFile.ts
packages/cli/src/models/network/NetworkController.ts
packages/cli/src/utils/prompt-migration.ts

Fixes https://github.com/zeppelinos/zos/issues/705. I also realized that we were not updating the `zosversion` attribute in the `zos.json` file in some cases. this PR also fixes that problem.

Fix error while trying to get zosversion from commmand

---

packages/cli/src/models/initializer/truffle/Truffle.ts
packages/cli/test/initializer/truffle/Truffle.test.js

Specify truffle config file name on error

---

packages/docs/docs/docs/deploying.md

Commented about not interacting with logic contracts in the deploying guide

---

packages/cli/test/scripts/migrate.test.js
packages/lib/contracts/mocks/WithStructInConstructor.sol
packages/lib/src/artifacts/Contract.ts
packages/lib/src/artifacts/Contracts.ts
packages/lib/src/utils/Transactions.ts
packages/lib/test/contracts/ProxyAdmin.test.js
packages/lib/test/contracts/application/App.test.js
packages/lib/test/contracts/application/ImplementationDirectory.test.js
packages/lib/test/contracts/application/ManagePackages.behavior.js
packages/lib/test/contracts/application/ManageProxies.behavior.js
packages/lib/test/contracts/application/Package.test.js
packages/lib/test/src/ProxyAdmin.test.js
packages/lib/test/src/artifacts/Contract.test.js
packages/lib/test/src/utils/Migrator.test.js

Sorry, I couldn't help myself ¯\_(ツ)_/¯

Parse ZosContract#new arguments

---

examples/truffle-migrate/.gitignore
examples/truffle-migrate/README.md
examples/truffle-migrate/migrations/2_deploy_v0.js
examples/truffle-migrate/migrations/3_deploy_v1.js
examples/truffle-migrate/package-lock.json
examples/truffle-migrate/package.json
examples/truffle-migrate/zos.json

Fix truffle-migrate example

---

packages/cli/src/commands/add.ts
packages/cli/src/commands/init.ts
packages/cli/src/commands/verify.ts
packages/cli/src/models/initializer/truffle/Truffle.ts
packages/cli/src/utils/prompt.ts
packages/cli/test/commands/verify.test.js
packages/cli/test/initializer/truffle/Truffle.test.js
packages/cli/test/utils/prompt.test.js

Fixes #719.
(btw, I don't care about uploading the etherscan API KEY in the gif :joy:) 
I'm aware that the command tests are failing. Will fix them soon :man_health_worker: .

Interactive verify

---

packages/cli/src/bin/options.ts
packages/cli/src/commands/link.ts
packages/cli/src/commands/unlink.ts
packages/cli/src/models/dependency/Dependency.ts
packages/cli/src/models/files/ZosPackageFile.ts
packages/cli/src/models/local/LocalController.ts
packages/cli/src/scripts/link.ts
packages/cli/src/scripts/unlink.ts
packages/cli/src/utils/prompt.ts
packages/cli/test/commands/link.test.js
packages/cli/test/models/ZosPackageFile.test.js

Fixes https://github.com/zeppelinos/zos/issues/720. Bonus track: interactive `unlink`ing.
Still polishing up some stuff.
EDIT: it seems that the `inquirer`'s checkbox feature does not work properly with `asciinema` :cry:

Interactive link and unlink

---

packages/docs/docs/docs/upgrading.md

initializeT

---

packages/lib/contracts/Initializable.sol

We have a hierarchy with more than 10 contracts, this optimization allowed us to significantly reduce gas cost

Optimize initializer modifier

---

packages/cli/src/models/compiler/Compiler.ts

Addresses #759 
This was a very quick fix and I have both Windows and Linux environments available at home. I've tested it in my Linux environment and everything seems fine; I'll try running the tests in my Windows environment tomorrow when I get home.

Fix `zos add` in Windows environments

---

packages/cli/src/models/Verifier.ts
packages/lib/src/artifacts/ZWeb3.ts

Add goerli network to ZWeb3.ts and Verifier.ts

Add goerli network #765

---

packages/cli/src/models/network/NetworkController.ts
packages/cli/test/scripts/push.test.js
packages/lib/src/utils/Logger.ts

Skip validation errors upon push force

---

packages/cli/contracts/mocks/ImplV1.sol
packages/cli/contracts/mocks/Libraries.sol
packages/lib/src/artifacts/Contract.ts

Link multiple solidity libraries

---

packages/docs/docs/website/versioned_docs/version-2.1.0/upgrading.md
packages/docs/docs/website/versioned_docs/version-2.2.0/upgrading.md

Fixes #779, thanks @SamSteele01!

Fix in upgrading guide

---

examples/truffle-migrate/index.js

Add test for truffle-migrate example

Add test to truffle-migrate example #767

---

packages/cli/src/models/TestHelper.ts
packages/lib/src/artifacts/ZWeb3.ts
packages/lib/test/src/artifacts/ZWeb3.test.js

Fixes #785. 
I also added a minor fix related to https://github.com/zeppelinos/zos/pull/770 and the `TestHelper` function.
Both changes have been included in `v2.2.2` release.

Fix in ZWeb3 initializer

---

packages/cli/truffle.js
packages/lib/truffle-config.js

Add forbidOnly flag to mocha via truffle config for cli and lib.

Fix CI if only is present on tests

---

packages/lib/contracts/mocks/WithLibrary.sol
packages/lib/test/src/utils/Transactions.test.js

Add test to check for unlinked libraries on deploy

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/bin/helpers.ts
packages/cli/src/bin/zos-cli.ts
packages/cli/src/commands/add.ts
packages/cli/src/commands/create.ts
packages/cli/src/commands/link.ts
packages/cli/src/commands/push.ts
packages/cli/test/bin/helpers.test.js

Fixes https://github.com/zeppelinos/zos/issues/646. Also, it could be useful for https://github.com/zeppelinos/zos/pull/792 and running `zos init` anywhere in the project :eyes:.

Implement function to look for project root dir

---

packages/cli/src/commands/index.ts
packages/cli/src/commands/transfer.ts
packages/cli/src/models/network/TransactionController.ts
packages/cli/src/prompts/prompt.ts
packages/cli/src/scripts/index.ts
packages/cli/src/scripts/transfer.ts
packages/cli/src/utils/units.ts
packages/cli/test/commands/share.js
packages/cli/test/commands/transfer.test.js
packages/cli/test/scripts/transfer.test.js
packages/lib/src/artifacts/ZWeb3.ts
packages/lib/src/utils/Migrator.ts
packages/lib/src/utils/Transactions.ts
packages/lib/test/src/artifacts/ZWeb3.test.js
packages/lib/test/src/utils/Transactions.test.js

Fixes #823 
I've started implementing a command in the cli to transfer an amount of ether/wei/gwei between accounts.
For this, I've created a `TransactionController` in the `cli` package that will probably host almost all functions that will interact with the `Transactions` lib's object.
A demo of how the command works:

Transfer command

---

packages/lib/package-lock.json
packages/lib/package.json

It was causing a critical security vulnerability upon npm audit.

Remove unused solidity coverage

---

packages/lib/src/artifacts/ZWeb3.ts
packages/lib/src/utils/Transactions.ts

More type support for TxParams

Add TxParams Type

---

packages/cli/src/models/local/KitController.ts
packages/cli/src/scripts/unpack.ts
packages/cli/test/scripts/unpack.test.js

* Fix #865 
* Fix #867 
* Adds`tutorial` shortcut for `unpack` command

Fix #865, #867; Adds tutorial kit shortcut

---

packages/cli/contracts/mocks/ImplV1.sol
packages/cli/src/models/network/NetworkController.ts
packages/cli/test/scripts/create.test.js

Fixes #860
Needs to be cherry-picked to release/2.3

Store proxy admin address on failed create

---

packages/cli/src/commands/create.ts
packages/cli/src/commands/push.ts
packages/cli/src/commands/update.ts
packages/cli/test/prompts/prompt.test.js
packages/cli/test/scripts/add.test.js

Fixes https://github.com/zeppelinos/zos/issues/820.

Run push command before updating an instance

---

packages/cli/src/bin/options.ts
packages/cli/src/commands/create.ts
packages/cli/src/commands/update.ts

Same as https://github.com/zeppelinos/zos/pull/876 (fixes #862) but for master branch.

Run push before creating an instance

---

packages/cli/src/bin/options.ts
packages/cli/src/commands/create.ts
packages/cli/src/commands/push.ts
packages/cli/src/commands/update.ts
packages/cli/test/scripts/add.test.js
packages/lib/package-lock.json
packages/lib/package.json
packages/lib/src/helpers/encodeCall.ts
packages/lib/test/contracts/application/App.test.js
packages/lib/test/contracts/application/ImplementationDirectory.test.js
packages/lib/test/src/project/ProxyAdminProject.test.js
packages/lib/test/src/project/SimpleProject.test.js
packages/lib/test/src/validations/Layout.test.js
packages/lib/test/src/validations/Validations.test.js

_Note for the reviewer: This PR can be dismissed if you review https://github.com/zeppelinos/zos/pull/879, as it includes the ported changes in this PR._
Fixes https://github.com/zeppelinos/zos/issues/862, ports https://github.com/zeppelinos/zos/pull/847 and removes some references to `lodash`.

[release/2.3] Run push before update and create

---

packages/cli/contracts/mocks/ImplV1.sol
packages/cli/src/bin/options.ts
packages/cli/src/commands/create.ts
packages/cli/src/commands/push.ts
packages/cli/src/commands/update.ts
packages/cli/src/prompts/init-params.ts
packages/cli/src/prompts/prompt.ts
packages/cli/test/commands/link.test.js
packages/cli/test/prompts/prompt.test.js
packages/cli/test/scripts/add.test.js
packages/lib/contracts/mocks/InitializableMock.sol
packages/lib/package-lock.json
packages/lib/package.json
packages/lib/src/artifacts/Contract.ts
packages/lib/src/helpers/encodeCall.ts
packages/lib/src/index.ts
packages/lib/src/utils/ABIs.ts
packages/lib/test/contracts/application/App.test.js
packages/lib/test/contracts/application/ImplementationDirectory.test.js
packages/lib/test/src/artifacts/Contract.test.js
packages/lib/test/src/project/ProxyAdminProject.test.js
packages/lib/test/src/project/SimpleProject.test.js
packages/lib/test/src/validations/Layout.test.js
packages/lib/test/src/validations/Validations.test.js

Fixes https://github.com/zeppelinos/zos/issues/859 for `release/2.3`. This was a tough one :stuck_out_tongue:.
_Note for the reviewer: I branched from https://github.com/zeppelinos/zos/pull/876 's branch, so the you can dismiss that PR if you want and just review this one._

[release/2.3] Differentiate constant and non constant functions

---

packages/cli/src/bin/zos-cli.ts

Fixes https://github.com/zeppelinos/zos/issues/868

Don't look for root dir on `zos unpack`

---

packages/cli/src/prompts/prompt.ts
packages/cli/test/prompts/prompt.test.js

Fixes bug on `source === 'fromLocal'` branch, and adds tests.
Fixes #884

[release/2.3] Fix prompt#contractsList with source fromLocal

---

packages/cli/src/models/files/ZosNetworkFile.ts
packages/cli/src/models/files/ZosPackageFile.ts

Fix zos.json error message

---

packages/cli/src/commands/link.ts
packages/cli/test/commands/link.test.js

Related to https://github.com/zeppelinos/zos/issues/872.

Remove useless question in `zos link` prompt

---

packages/cli/src/commands/link.ts
packages/cli/test/commands/link.test.js

Related to https://github.com/zeppelinos/zos/issues/872

[release/2.3] Remove useless question in zos link

---

packages/cli/src/commands/create.ts

Fixes https://github.com/zeppelinos/zos/issues/858 for master.

Run contracts compilation on create

---

packages/cli/src/commands/create.ts

Fixes https://github.com/zeppelinos/zos/issues/858 for the `release/2.3` branch

[release 2.3] Run contracts compilation on create

---

packages/cli/src/commands/add.ts
packages/cli/src/commands/remove.ts
packages/cli/src/commands/verify.ts
packages/cli/src/prompts/prompt.ts
packages/cli/src/scripts/verify.ts
packages/cli/test/prompts/prompt.test.js

Fixes https://github.com/zeppelinos/zos/issues/899. I added a new contract list type (`notAdded`) and also renamed the already defined types.

Add a new contract list type for getting non-added contracts

---

packages/cli/src/commands/add.ts
packages/cli/src/commands/remove.ts
packages/cli/src/commands/verify.ts
packages/cli/src/prompts/prompt.ts
packages/cli/src/scripts/verify.ts
packages/cli/test/prompts/prompt.test.js

Fixes #899 for the `release/2.3` branch.

[release 2.3] Add a new contract list type for getting non-added contracts

---

packages/cli/src/models/files/ZosPackageFile.ts
packages/cli/src/models/local/ContractManager.ts
packages/cli/src/models/local/LocalController.ts
packages/cli/test/models/ContractManager.test.js
packages/cli/test/scripts/add.test.js

Handle relative and absolute paths in isLocalContract

---

packages/cli/src/models/config/ConfigManager.ts

Create `contracts` folder on `zos init`

---

packages/cli/src/models/compiler/solidity/ResolverEngineGatherer.ts
packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js

Outputs: `Could not find file Foo.sol in folder contracts (imported from contracts/Counter.sol)`
Fixes #954

Better error msg on failed import

---

packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts
packages/cli/test/mocks/mock-stdlib-empty/package.json
packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js

Handle compile commands when there are no sources

---

packages/lib/src/proxy/ProxyFactory.ts

Fix getting proxy address from ProxyCreated event

---

packages/cli/src/models/config/blueprint.networks.js
packages/cli/test/config/ZosConfig.test.js

Fixes https://github.com/zeppelinos/zos/issues/972.

Change dev network name & port in blueprint file

---

packages/cli/src/models/network/Session.ts
packages/lib/test/src/utils/Logger.test.js

Fixes https://github.com/zeppelinos/zos/issues/974. Also, I removed an unused test that was merged on https://github.com/zeppelinos/zos/pull/980.

Log session info only once

---

packages/lib/package-lock.json
packages/lib/package.json
packages/lib/src/proxy/ProxyFactory.ts
packages/lib/src/utils/Solidity.ts

Fixes https://github.com/zeppelinos/zos/issues/944.
The verifier is not working though. It's probably related to how we are picking the default compiler options in `cli/src/commands/verify.ts`.

Fix Verifier when using custom config

---

packages/cli/src/commands/add.ts
packages/cli/src/commands/create.ts
packages/cli/src/commands/init.ts
packages/cli/src/commands/update.ts
packages/cli/src/commands/verify.ts
packages/cli/src/models/compiler/solidity/CompilerProvider.ts
packages/cli/src/models/dependency/Dependency.ts
packages/cli/src/models/local/LocalController.ts
packages/cli/src/models/network/NetworkController.ts
packages/cli/src/models/network/TransactionController.ts
packages/cli/src/prompts/prompt.ts
packages/cli/src/scripts/add.ts
packages/cli/src/scripts/remove.ts
packages/cli/test/prompts/prompt.test.js
packages/cli/test/scripts/call.test.js
packages/cli/test/scripts/push.test.js
packages/lib/package-lock.json
packages/lib/package.json
packages/lib/src/application/App.ts
packages/lib/src/project/AppProject.ts
packages/lib/src/project/BaseSimpleProject.ts
packages/lib/src/project/ProxyAdminProject.ts
packages/lib/src/proxy/ProxyAdmin.ts
packages/lib/src/utils/ABIs.ts

Fixes https://github.com/zeppelinos/zos/issues/960.
- Implemented Manu's suggestions in both inputs and outputs.
- Updated spinnies to `v0.4.1`, which handles spinners texts with line breaks properly
- Improve the message logged when creating an instance calling a function that does not receive arguments.

Improve inputs and outputs text messages

---

packages/cli/src/commands/call.ts
packages/cli/src/commands/send-tx.ts

Fixes https://github.com/zeppelinos/zos/issues/994.

Fix proxies prompt choices on call and send-tx commands 

---

packages/cli/src/commands/verify.ts

Load compiler settings from zos json for verification

---

packages/cli/src/commands/set-admin.ts
packages/cli/src/commands/update.ts
packages/cli/src/prompts/prompt.ts

Show minimal proxies on zos send-tx and call

---

packages/cli/package-lock.json
packages/cli/package.json

Related to https://github.com/SBoudrias/Inquirer.js/issues/812, Fixes https://github.com/zeppelinos/zos/issues/1025, Fixes https://github.com/zeppelinos/zos/issues/1027

Update inquirer version to ^6.4.1

---

packages/cli/docs/bin/docs.ts
packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/bin/program.ts
packages/cli/src/commands/create.ts
packages/cli/src/commands/session.ts
packages/cli/src/commands/update.ts

Fixes https://github.com/zeppelinos/zos/issues/1026. Also, cherry picked https://github.com/zeppelinos/zos/commit/b6d7d6d8f065c685e381e931012ab712c15a466f.

Remove status command from `zos --help` and doc generator

---

packages/cli/src/models/config/TruffleConfig.ts
packages/cli/test/config/TruffleConfig.test.js

Fixes https://github.com/zeppelinos/zos/issues/1029

Throw error if truffle config cannot be loaded

---

packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/models/compiler/solidity/ResolverEngineGatherer.ts
packages/cli/src/models/compiler/solidity/SolidityContractsCompiler.ts
packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts

Adds fix to handle Windows-like paths.
Fixes #1049

Use OpenZeppelin fork of resolver engine

---

.githooks/pre-commit
package-lock.json
package.json
packages/cli/package-lock.json
packages/cli/package.json
packages/lib/package-lock.json
packages/lib/package.json

* Use husky to run git hooks – no need to install anything.
* Use lint-staged to lint only changed files not entire project
* Compiles entire project using TypeScript on each commit

Adds frictionless support for git hooks and linting

---

packages/docs/docs/docs/architecture.md

Adding information about ProxyAdmin.sol

Adding ProxyAdmin.sol

---

LICENSE
packages/cli/LICENSE
packages/docs/LICENSE
packages/lib/LICENSE

Modified LICENSE files as discussed offline with John.

Update LICENSE files

---

packages/cli/src/models/local/ContractManager.ts

Get contracts folder from project root directory

---

packages/cli/src/models/config/ConfigManager.ts
packages/cli/src/models/dependency/Dependency.ts
packages/cli/src/models/files/NetworkFile.ts
packages/cli/src/models/files/ProjectFile.ts
packages/cli/src/models/local/LocalController.ts
packages/cli/test/mocks/networks/network-deprecated-manifest-version.zos.test.json
packages/cli/test/mocks/packages/package-deprecated-manifest-version.zos.json
packages/cli/test/models/NetworkFile.test.js
packages/cli/test/models/ProjectFile.test.js

Add support for deprecated manifest version (zosversion)

---

packages/docs/docs/docs/architecture.md

Adding ProxyFactory information

Adding ProxyFactory

---

packages/docs/docs/docs/create_zepkit.md

Adding "build your own zepkit" guide

Adding create_zepkit.md

---

packages/cli/src/models/local/KitController.ts
packages/cli/src/models/local/LocalController.ts
packages/cli/src/models/network/NetworkController.ts
packages/cli/src/models/network/Session.ts
packages/cli/src/prompts/prompt.ts
packages/cli/src/scripts/remove.ts
packages/cli/test/scripts/create.test.js
packages/cli/test/scripts/verify.test.js

Rename command suggestions from zos to openzeppelin

---

packages/cli/src/models/dependency/Dependency.ts
packages/cli/test/mocks/packages/package-with-newer-stdlib.zos.json
packages/cli/test/models/Dependency.test.js

Check outdated dependencies to push (#1119)

---

packages/cli/src/models/network/NetworkController.ts
packages/cli/test/scripts/create.test.js

Set proxy admin address in proxy info on first create

---

examples/cli-create2/package-lock.json
examples/cli-create2/package.json
examples/first-project/package-lock.json
examples/first-project/package.json
examples/lib-complex/package-lock.json
packages/cli/package-lock.json
packages/cli/package.json
packages/lib/package-lock.json
packages/lib/package.json
tests/cli/workdir/package-lock.json

Let's give the new stable web3 a shot!

Migrate to web3 1.2.0

---

packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts

Format compiler output

---

tests/cli/test/src/integration.test.js

Rename test to oz

---

packages/cli/src/models/compiler/Compiler.ts

Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1183.

Set expected default values for compiler #1183

---

packages/docs/modules/ROOT/pages/gsn-dapp.adoc

React dependency has been moved to submodule. Docs reflect that change.

Update network.js docs

---

.circleci/config.yml

Fixes issue with CI where truffle binary was missing

Bust CI cache

---

packages/docs/modules/ROOT/pages/network-js.adoc

First draft of Network.js documentation.  
Similar to README currently, so may need to be structured more like a guide with example code?

abcoathup add network js doc

---

packages/docs/modules/ROOT/pages/public-deploy.adoc

Remove duplicate section from merge error

public-deploy.adoc remove duplicate section

---

.circleci/config.yml
package.json
packages/cli/package.json
packages/cli/src/interface/ValidationLogger.ts
packages/cli/src/models/Verifier.ts
packages/cli/src/models/dependency/Dependency.ts
packages/cli/src/models/network/NetworkController.ts
packages/cli/test/mocks/config-files/networks.js
packages/cli/test/mocks/config-files/truffle.js
packages/cli/test/models/compiler/solidity/SolidityContractsCompiler.test.js
packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js
packages/cli/test/scripts/push.test.js
packages/cli/test/scripts/set-admin.test.js
packages/cli/test/scripts/update.test.js
packages/lib/package.json
packages/lib/src/utils/ABIs.ts
packages/lib/src/utils/ContractAST.ts
packages/lib/test/src/validations/Layout.test.js
packages/lib/test/src/validations/Storage.test.js
tsconfig.json

- Fixes all errors
- Adds step to check linter in the CI

Fix linter errors & enforce linter on CI

---

package.json
packages/cli/package.json
packages/lib/package.json
yarn.lock

We have decided not to rely on git hooks to enforce rules, and instead rely on CI to do it.

Remove Husky

---

packages/cli/src/models/local/KitController.ts
packages/cli/src/models/network/NetworkController.ts
packages/cli/src/scripts/add.ts
packages/cli/src/utils/input.ts
packages/lib/src/project/AppProject.ts
packages/lib/src/project/BasePackageProject.ts
packages/lib/src/utils/Logger.ts

I changed the object into a class with static functions because that way `this` is typed correctly.
I have not reviewed the interface so I'm not marking #1315 as fixed.

Add types to Loggy

---

packages/cli/src/commands/deploy/spec.ts

Fixes #1417 
The surface problem was that we were replacing the `network` option in the parameters with the normalized network name, and when forwarding to the `create` command it failed because the normalized name was not one of the user's networks.
The deeper problem was that we were initializing and then re-initializing the ConfigManager, first in `deploy` and then in `create`, in these cases. I made the initialization happen only on `deploy`.

Fix deploy bug for upgradeable and minimal deploys

---

packages/cli/package.json
packages/cli/solc/solc
yarn.lock

Prevents "soljson.Pointer_stringify is not a function" error
Fixes #1406

Update solc-wrapper version

---

packages/cli/package.json
yarn.lock

Update fuzzy parser dependency

---

examples/cli-create2/package.json
examples/creating-instances-from-solidity/package.json
examples/first-project/package.json
examples/linking-contracts/package.json
examples/truffle-migrate/package.json
examples/upgrades-library/package.json
lerna.json
packages/cli/changelog.md
packages/cli/package.json
packages/lib/changelog.md
packages/lib/package.json
packages/lib/src/artifacts/ZWeb3.ts
tests/cli/test/package.json
tests/cli/workdir/package.json
tests/kits/test/package.json
tests/mocks/mock-dependency/package-lock.json
tests/mocks/mock-dependency/package.json
tests/mocks/mock-solc-0.6/package.json

Use a merge commit instead of squashing to preserve history

Merge release 2.7.0 into master

---

packages/cli/package.json
yarn.lock

Updates grpc transitive dependency, which was causing install issues in node 13
Fixes #1419

Update firebase dependency

---

packages/cli/src/commands/verify/spec.ts

Port fix for deploy spec to verify spec

---

packages/cli/src/models/network/TransactionController.ts
packages/cli/src/test/scripts/call.test.js
packages/cli/src/test/scripts/send-tx.test.js

Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1479.

Improve error message for regular instances

---

packages/cli/src/prompts/prompt.ts
packages/cli/src/test/prompts/prompt.test.js
tsconfig.json

Add proxyInfo test

---

packages/cli/src/commands/deploy/spec.ts
packages/cli/src/prompts/choices.ts
packages/cli/src/register-command.ts

Added a description in parentheses to explain what each deployment kind means. The descriptions themselves need work.

Add descriptions of deployment kinds

---

packages/cli/src/commands/deploy/spec.ts

Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1520

Fix docs for deploy kind

---

examples/linking-contracts/.gitignore
examples/linking-contracts/.openzeppelin/project.json
examples/linking-contracts/README.md
examples/linking-contracts/contracts/TokenExchange.sol
examples/linking-contracts/package.json
packages/cli/docs/modules/ROOT/pages/dependencies.adoc
packages/lib/docs/modules/ROOT/pages/writing-upgradeable.adoc

Update writing-upgradeable.adoc
Update writing-upgradeable.adoc
Update dependencies.adoc
Update TokenExchange example

Update docs for OpenZeppelin Contracts Ethereum Package v3.0

---

packages/lib/docs/modules/ROOT/pages/creating-upgradeable-from-solidity.adoc
packages/lib/docs/modules/ROOT/pages/proxies.adoc
packages/lib/docs/modules/ROOT/pages/writing-upgradeable.adoc

Fix typos
Fix code typo - reported by community member via Intercom
Format code
Add SPDX license identifiers
Update to Solidity 0.6 (where possible)
Update to OpenZeppelin Contracts 3.x/OpenZeppelin Contracts Ethereum Package
Update samples to use latest CLI output

Update Upgrade docs

---

packages/lib/README.md

Update example to be based on: https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/examples/upgrades-library/index.js

Update usage example in lib\README.md

---

examples/upgrades-library/README.md

Contracts should be compiled before running index.js.

fix upgrades-library README.md
