OpenZeppelin/openzeppelin-sdk

packages/docs/docs/docs/advanced.md
Added subsection to the advanced guide that speaks to how 'initialize' functions sometimes must be called manually in a user's unit tests.
=> Calling Initialize Functions Manually in Your Unit Tests

packages/lib/src/utils/Transactions.js
Related to https://github.com/zeppelinos/zos-cli/issues/334
Implemented two functions for wrapping deploy and sendTransaction functions (renamed to _deploy and _sendTransaction) and retrying their original behaviour if a network error is thrown.
For getting these changes to work, https://github.com/zeppelinos/zos/pull/25 should be merged first.
=> Implement wrapper functions for managing retries

packages/cli/src/models/dependency/Dependency.js, packages/cli/src/models/files/ZosNetworkFile.js, packages/cli/src/models/files/ZosPackageFile.js, packages/cli/src/models/local/LocalAppController.js, packages/cli/src/models/network/NetworkAppController.js, packages/cli/src/scripts/status.js, packages/cli/test/scripts/status.test.js
Re-enables the `status` command that had been disabled for multiple dependencies on #17 .
=> Status command for multiple dependencies

packages/cli/src/commands/index.js, packages/cli/src/commands/set-admin.js, packages/cli/src/models/files/ZosNetworkFile.js, packages/cli/src/models/network/NetworkAppController.js, packages/cli/src/scripts/set-admin.js, packages/cli/test/commands/setAdmin.test.js, packages/cli/test/commands/share.js, packages/cli/test/scripts/set-admin.test.js, packages/cli/test/scripts/update.test.js, packages/lib/src/project/AppProject.js
Add new `set-admin` command to change admin ownership of a proxy. The command requires a `-y` or `--yes` flag to be actually run, otherwise it cowardly refuses. It can be run either with an address, or a contract name (optionally namespaced by a package). For instance:
```bash
$ zos session ...
$ zos set-admin MyContract $NEWADMIN -y
$ zos set-admin OpenZeppelin/ERC20 $NEWADMIN -y
$ zos set-admin 0x40 $NEWADMIN -y
```
Fixes #3
=> Change admin command

packages/cli/src/commands/init.js, packages/cli/src/commands/link.js, packages/cli/src/models/local/LocalAppController.js, packages/cli/src/scripts/init.js, packages/cli/src/scripts/link.js, packages/cli/test/commands/init.test.js, packages/cli/test/commands/link.test.js, packages/cli/test/scripts/bump.test.js, packages/cli/test/scripts/create.test.js, packages/cli/test/scripts/init.test.js, packages/cli/test/scripts/link.test.js, packages/cli/test/scripts/status.test.js, packages/cli/test/scripts/update.test.js
Example usage:
```console
foo@bar:~$ zos link openzeppelin-zos gnosis-safe
```
or
```console
foo@bar:~$ zos init MyUpgradeableProjectWithDependencies 0.0.1 --link openzeppelin-zos,gnosis-safe
```
=> Extend link CLI command to support multiple dependencies

packages/cli/src/commands/set-admin.js, packages/cli/src/models/files/ZosNetworkFile.js, packages/cli/src/models/network/NetworkAppController.js
Builds on #47 adding suggestions by @facuspagnuolo.
=> Implement minor changes on change-admin command

packages/docs/docs/docs/advanced.md, packages/docs/docs/docs/building.md, packages/docs/docs/docs/writing_contracts.md, packages/docs/docs/website/i18n/en.json, packages/docs/docs/website/sidebars.json
Includes a section on using Initializable (fixes #48), another on
creating contracts from code (since I was at it), and yet another
explanation on preserving the storage layout (since it has been
a topic of confusion).
=> Add guide on writing upgradeable contracts

packages/cli/src/utils/runWithTruffle.js
Fixes https://github.com/zeppelinos/zos/issues/98.
It seems to be a `truffle-hdwallet-provider` well known problem, as mentioned [here](https://github.com/rhlsthrm/truffle-hdwallet-provider-privkey#notes).
=> Change `from` parameter value to lower case

packages/cli/src/utils/contracts.js, packages/cli/test/utils/contracts.test.js
Fixes https://github.com/zeppelinos/zos/issues/38.
@spalladino should we add an option parameter to the `bytecodeDigest` function, e.g., `{ removeSwarmHash: true/false }` to decide whether to remove it or not?
=> Remove swarm hash from bytecode before hashing it

packages/cli/src/models/dependency/Dependency.js, packages/cli/src/models/files/ZosNetworkFile.js, packages/cli/src/models/status/StatusChecker.js, packages/cli/src/models/status/StatusComparator.js, packages/cli/src/models/status/StatusFetcher.js, packages/cli/test/models/StatusComparator.test.js, packages/cli/test/models/StatusFetcher.test.js, packages/lib/src/app/App.js
I'm creating this pull request because Github won't let me reopen https://github.com/zeppelinos/zos/pull/99  :cat: 
---
- Adapt `StatusChecker`, `StatusComparator` and `StatusFetcher` classes to work with the new contracts architecture and lib models implemented by @spalladino to support multiple dependencies.
- Implement multiple dependencies checker, fetcher and comparator functions.
=> Fix status checker, comparator and fetcher

examples/lib-complex/index.js, packages/cli/src/models/dependency/Dependency.js, packages/cli/src/models/network/NetworkAppController.js, packages/cli/src/models/network/NetworkBaseController.js, packages/cli/src/models/network/NetworkLibController.js, packages/cli/src/scripts/status.js, packages/cli/test/models/Dependency.test.js, packages/cli/test/scripts/push.test.js, packages/lib/src/app/App.js, packages/lib/src/project/AppProject.js, packages/lib/src/project/LibProject.js, packages/lib/src/utils/errors/DeployError.js, packages/lib/test/src/app/App.test.js, packages/lib/test/src/project/AppProject.test.js, packages/lib/test/src/project/LibProject.test.js
=> Preserve App, Package and Directory addresses

packages/cli/src/models/status/StatusChecker.js
Instead of calling deprecated `AppProject`/`LibProject`  `fetch` method.
=> Call `deployOrFetch` method in StatusChecker

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/models/files/ZosNetworkFile.js, packages/cli/src/models/network/NetworkBaseController.js, packages/cli/src/models/status/StatusChecker.js, packages/cli/src/models/status/StatusFetcher.js, packages/cli/test/models/StatusComparator.test.js, packages/cli/test/models/StatusFetcher.test.js, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/src/index.js, packages/lib/src/project/SimpleProject.js, packages/lib/src/proxy/Proxy.js, packages/lib/src/utils/Bytecode.js, packages/lib/src/utils/Solidity.js, packages/lib/test/src/project/PackageProject.behavior.js, packages/lib/test/src/project/ProxyProject.behaviour.js, packages/lib/test/src/project/SimpleProject.test.js, packages/lib/test/src/utils/Bytecode.test.js
Reuses the same logic contract for multiple proxies. Supports tracking bytecode changes to optionally redeploy if the contract class changes. And since we were at it, use upgradeAndCall from Proxy to make atomic upgrades.
Fixes #72
=> Track logic contracts in SimpleProject

packages/vouching/contracts/Vouching.sol, packages/vouching/test/Vouching.test.js
This PR includes a possible implementation that tackles #132 . I'm opening it to start discussing the issue over real code.
Here I'm basically indexing by the keccak256 hash of the `name` argument. The actual name (not the hash) is logged in the `DependencyCreated` event. Tests were updated as well.
Not entirely sure of the efficiency of the implementation though, since we'd be hashing the `name` everytime the contract fires an event. I'm eager to hear reviews and comments on this.
~EDIT: note that I'm merging into `vouching`~
=> Index names in Vouching events using name hash

packages/cli/src/models/network/NetworkBaseController.js, tests/cli-app/files/package.json.v1, tests/cli-app/files/package.json.v2, tests/cli-app/test/integration.test.js
Integration tests were being run on version 1.4.2, instead of the latest
code in each commit. This commit changes the dependency to target
2.0.0-alpha.0 instead.
Include fixes for integration tests
- Rename flag deploy-stdlib to deploy-libs
- Fix zos-lib import in CLI
- Use latest version of packages in integration tests
- Use fully qualified name of contracts in tests
=> Run integration tests on latest version

packages/cli/src/models/network/NetworkAppController.js, packages/cli/src/models/network/NetworkBaseController.js, packages/cli/src/models/network/NetworkLibController.js, packages/cli/src/models/network/ProjectDeployer.js, packages/cli/src/scripts/status.js
In case the deployment or fetch of an App/Lib failed, we were registering the partial deploy but the flow continued as if everything has worked fine, adding a check to re-throw if necessary
Fixes https://github.com/zeppelinos/zos/issues/172 as well
=> Re-throw App or Lib deployment errors

packages/lib/contracts/Initializable.sol
This change is required from oz-zos to handle certain scenarios
with multiple inheritance. Original commit by @frangio is:
https://github.com/OpenZeppelin/openzeppelin-zos/commit/6e0ace1914f120fb24b2c1b648b08e4084011209#diff-0e8e787a34109f83dafec072d3664194
=> Check isConstructor for running initializable

packages/lib/package-lock.json, packages/lib/package.json, packages/lib/src/helpers/copyContract.js, packages/lib/src/helpers/sleep.js, packages/lib/src/utils/Transactions.js, packages/lib/test/src/utils/Transactions.test.js
If a transaction to be sent fails, the error we'll actually get is
an 'always failing transaction' on the estimateGas we sent first.
However, we want to retry some transactions, as they may depend on
a previous tx being mined, which may have not propagated yet.
To handle these scenarios, we add 3 retries to gas estimation,
separated by a small sleep interval.
Fixes #192
=> Retry gas estimation

packages/lib/contracts/Initializable.sol, packages/lib/test/contracts/upgradeability/AdminUpgradeabilityProxy.test.js
Created from the discussion in https://github.com/OpenZeppelin/openzeppelin-zos/pull/29
This is the same gap all `openzeppelin-zos` contracts have. My editor also removed some trailing whitespace, but I can undo that if you have strong feelings about it :stuck_out_tongue:
=> Added a storage gap at the end of Initializable's storage layout.

packages/vouching/contracts/Vouching.sol, packages/vouching/test/contracts/Vouching.test.js
Fixes #202.
I considered leaving a sentinel value to signal a name had been taken, but both `owner` and `address` need to be obviously zeroed out, and `stake` can be 0 (if `minimalStake` is 0), so I opted for adding an extra field. This should have a minimal impact on gas costs, since `used` is packed alongside `owner`, emitting a single `SSTORE`/`SLOAD` opcode when accessing (this was verified experimentally).
I'm not 100% sure on the name (maybe `nameTaken`?), but this is an internal detail and not part of the API.
=> Removed dependency names can no longer be reused.

packages/lib/contracts/application/App.sol, packages/lib/contracts/upgradeability/AdminUpgradeabilityProxy.sol, packages/lib/contracts/upgradeability/UpgradeabilityProxy.sol
Despite the ABI not going to change for a while, we should still link to the docsite relevant to our compiler version (`develop` has v0.5.0 information).
=> Pinned the Solidity doc links to v0.4.24

packages/lib/contracts/upgradeability/AdminUpgradeabilityProxy.sol
Fixes issue [zOS2L-O01] of the Nomic audit (part of #205).
There were no tests for this, but I'm not sure what they'd look like, since we'd be testing the existence of the transparent proxy mechanism: maybe have the call query `admin()` and check that it reverts if the proxy is not its own admin, and doesn't otherwise?
=> upgradeToAndCall now delegatecalls instead of externally calling.

packages/vouching/contracts/Vouching.sol, packages/vouching/contracts/mocks/DependencyMock.sol, packages/vouching/test/contracts/Vouching.test.js
Fixes issue [zOS2V-O03] of the Nomic audit (part of #203).
=> Vouching.create now requires the dependency address to be a contract.

packages/cli/src/bin/options.js, packages/cli/src/commands/add.js
Related to https://github.com/zeppelinos/zos/issues/67, this PR doesn't fix it though, as there is nothing to fix, but adds the `skip-compile` option to the `withPushOptions` function, to have the posibility to whether run `truffle compile` or not.
=> Add skip-compile option to push options

packages/lib/contracts/application/Package.sol
Package.sol imports ImplementatioProvider.sol and doesn't use it (probably did before). Now it simply tracks contract addresses within its Version structs.
App.sol know about ImplementationProviders, while Package.sol does not.
=> Removed unnecessary import.

packages/cli/src/commands/check.js, packages/cli/src/commands/index.js, packages/cli/src/models/files/ZosPackageFile.js, packages/cli/src/models/local/LocalBaseController.js, packages/cli/src/scripts/add.js, packages/cli/src/scripts/check.js, packages/cli/test/commands/check.test.js, packages/cli/test/commands/share.js, packages/cli/test/scripts/check.test.js, packages/lib/src/utils/Contracts.js
Adds a new check command that outputs validation errors for all contracts in the project, or allows for a single contract to be specified.
Depends on pull request from branch feature/validate-contract-on-push. Merge after that one.
=> Add new check command

packages/cli/src/models/network/NetworkAppController.js, packages/cli/test/scripts/create.test.js, packages/cli/test/scripts/update.test.js
Changes both create and update commands to retrieve the package version
of either the project package or the dependency package when annotating
the proxy version in the network json file.
Fixes #267
=> Use version of dependency for identifying proxies in network json file

packages/lib/contracts/mocks/StorageMocksForComparison.sol, packages/lib/src/validations/Storage.js, packages/lib/test/src/validations/Layout.test.js, packages/lib/test/src/validations/Storage.test.js
Given a contract with a mapping or array (not struct), the check for
whether it contained structs or enums failed if there was no variable
with the same type as the value type of the mapping or array. For
instance, a contract with a variable of type `array(string)` and another
`string` would work, but a contract with just `array(string)` would
fail.
=> Fix storage layout parsing when there are complex types

packages/cli/src/models/errors/ScriptError.js, packages/cli/src/scripts/create.js, packages/cli/src/scripts/freeze.js, packages/cli/src/scripts/publish.js, packages/cli/src/scripts/pull.js, packages/cli/src/scripts/push.js
We were loosing the original error stack trace due to the `ScriptError` implementation. This PR overwrites the `ScriptError` stack trace with the original one.
=> Preserve stack trace when using ScriptError

packages/cli/src/models/files/ZosNetworkFile.js, packages/cli/src/models/network/NetworkAppController.js, packages/cli/src/models/network/NetworkBaseController.js, packages/cli/test/scripts/push.test.js
Previously the check was done only when uploading contracts, and caused
the solidity lib upload to fail with an EVM revert.
Fixes #266
=> Check if package is frozen before uploading solidity libs

packages/lib/src/project/AppProject.js, packages/lib/src/project/LibProject.js, packages/lib/src/utils/errors/DeployError.js
We were losing `zos-lib` stack trace when using `DeployError`. This PR overwrites the `DeployError` stack trace with the original one.
=> Preserve stack trace when using DeployError

packages/docs/docs/docs/writing_contracts.md
I think it's better not to say that some constructors can be executed. For zOS, all should be initializers.
[CI skip]
=> docs: remove confusing note about contructors

packages/docs/docs/docs/new_2.x
=> docs: the description of the new 2.x commands is no longer on the page

packages/docs/docs/docs/erc20_onboarding.md, packages/docs/docs/docs/new_2.md, packages/docs/docs/docs/writing_contracts.md, packages/docs/docs/website/versioned_docs/version-1.0.0/building.md, packages/docs/docs/website/versioned_docs/version-1.0.0/low_level_contract.md
Fix #320 
Note that the issue just mentioned `#initializers-vs-constructors`, but this PR also fixes links to other sections of `advanced.md` that were moved to `proxies.md`:
=> Corrected links to sub-sections of advanced.md that were removed.

packages/cli/src/models/truffle/blueprint.truffle.js
Fixes https://github.com/zeppelinos/zos/issues/311.
=> Add default gasPrice to truffle.js blueprint.

packages/cli/test/scripts/create.test.js, packages/lib/src/helpers/encodeCall.js
Apparently ethereumjs-abi is using a version of bignumber that fails to
properly parse a number of the form '20e10'. To workaround this, we
pre-parse all arguments, pass them through bignumber, and then send them
to the encode function.
Fixes #327
=> Handle scientific notation in argument initializers

packages/cli/src/interface/ValidationLogger.js, packages/cli/test/interface/ValidationLogger.test.js, packages/docs/docs/docs/writing_contracts.md
Updates all validation messages from ValidationLogger to simplify them
and add links to documentation. Add to writing contracts doc info on any
validations missing.
Fixes #248
=> Review security warnings messages and capture them in docs

packages/docs/docs/website/package-lock.json, packages/docs/docs/website/package.json, packages/docs/docs/website/siteConfig.js
Added https://github.com/pospi/highlightjs-solidity as suggested in the issue. The end result looks like this:
We can still make more improvements by playing with themes (see the Styles section in the [demo page](https://highlightjs.org/static/demo/)). I'll loop in @blancoagostina to discuss that.
Fixes #341
=> Add solidity syntax highlighter to docs

packages/docs/docs/docs/publish.md
=> docs: explain why the config files must be published

packages/cli/src/models/status/StatusChecker.js, packages/cli/src/models/status/StatusComparator.js, packages/cli/src/models/status/StatusFetcher.js
Caused `Web3ProviderEngine does not support synchronous requests` when
running status --fix with async providers.
Fixes #387
=> Promisify call to web3 getCode on status fix

packages/docs/docs/docs/testing.md
There was a whitespace at the beginning of the `testing.md` section that was causing trouble when trying to build the doc site (notice that the latest deploy does not have this section updated). I'm redeploying after merging this PR.
=> Remove whitespace from beginning of testing .md

packages/cli/changelog.md, packages/lib/changelog.md
=> Changelog for v2.0.1

packages/cli/src/models/network/NetworkAppController.js
Upon creating a proxy for a contract, the current implementation clears
all deployment information before adding the new one. It should only
replace the info for the current network.
=> Do not delete deployment info from other networks in truffle artifacts

packages/cli/src/commands/verify.js, packages/cli/src/models/Verifier.js, packages/cli/src/models/network/NetworkBaseController.js, packages/cli/src/scripts/verify.js, packages/cli/src/utils/sleep.js, packages/cli/test/scripts/verify.test.js
Related to https://github.com/zeppelinos/zos/issues/251
Etherscan works with apikey, so this update also add --api-key option to verify command. Example:
`zos verify --remote etherscan --api-key <api key> -n rinkeby <contract name>`
=> Add Etherscan as remote verification application for 'verify' command

packages/lib/src/utils/Transactions.js, packages/lib/test/src/utils/Transactions.test.js
Fixes #297 and #441 
The problem was not related with dependencies as mentioned in #297, but with contract method calls when using `truffle-hdwallet-provider`. For some reason, `web3.eth.estimateGas` fails to execute in this specific case, but the `estimateGas` function from the method (i.e., `mycontract.myFunction.estimateGas`) doesn't.
=> Use contract method `estimateGas` function instead of `web3.eth.estimateGas` for contract method calls

packages/docs/docs/docs/mainnet.md
Attempting to deploy (and EVM package) using zos following the mainnet recomendations as listed here fails with the error: 
Cowardly refusing to execute transaction with excessively high default gas price of 100 gwei. Consider explicitly setting a different gasPrice value in your truffle.js config file. You can check reasonable values for gas price in https://ethgasstation.info/.
We need to set the gas value and gas price. I added an example above, however this is not always enough either and can fail with either: 
ProviderError: insufficient funds for gas * price + value
or
Error: Contract transaction couldn't be found after 50 blocks
or
Error: ProviderError: gas required exceeds allowance or always failing transaction
They contract may still be deployed however in the case of the final …
=> This process does not work with ZOS

packages/docs/docs/docs/upgrading.md, packages/docs/docs/website/versioned_docs/version-2.0.0/upgrading.md
myContract.x().toString() does not return a number, it returns a promise object. 
myContract.x().toString() returns a pending promise: '[object Promise]'
myContract.x() returns a bigNumber object: BigNumber { s: 1, e: 1, c: [ 42 ] }
To return a string format of the returned promise object we need: 
myContract.x().then((num)=> num.toString()) will return '42'
=> Fix BigNumber promise call in doc site example

packages/lib/package.json
=> Delete mock contracts when publishing package

packages/lib/src/utils/Transactions.js, packages/lib/test/src/utils/Transactions.test.js
We are requesting Ethgasstation's API to get a recommended `gas price` value for mainnet transactions, but the HTTP response is not being properly handled. This PR fixes that and updates the test suite.
=> Fix ethgasstation HTTP response handling

packages/cli/src/commands/verify.js, packages/cli/test/commands/verify.test.js
- Add a simple test case for the `verify` command
- Take only necessary attributes from `commander.js` options
- Change `Initializer.init()` in favour of `Initializer.call()`
=> Add tests to verify command and fix initializer call.

packages/cli/package-lock.json, packages/lib/scripts/test.sh, packages/lib/src/application/ImplementationDirectory.ts, packages/lib/src/application/Package.ts, packages/lib/src/artifacts/BuildArtifacts.ts, packages/lib/src/artifacts/ContractFactory.ts, packages/lib/src/artifacts/ZWeb3.ts, packages/lib/src/helpers/advanceBlock.ts, packages/lib/src/helpers/encodeCall.ts, packages/lib/src/project/AppProject.ts, packages/lib/src/project/SimpleProject.ts, packages/lib/src/proxy/Proxy.ts, packages/lib/src/utils/ABIs.ts, packages/lib/src/utils/Addresses.ts, packages/lib/src/utils/ContractAST.ts, packages/lib/src/utils/FileSystem.ts, packages/lib/src/utils/Logger.ts, packages/lib/src/utils/Semver.ts, packages/lib/src/utils/Transactions.ts, packages/lib/src/validations/InitialValues.ts, packages/lib/src/validations/Initializers.ts, packages/lib/src/validations/Instructions.ts, packages/lib/src/validations/Layout.ts, packages/lib/src/validations/Storage.ts, packages/lib/src/validations/index.ts, packages/lib/tsconfig.json, packages/lib/tsconfig.test.json, tslint.json
Closes #475 
Closes #484 
This PR does the following things:
1) Reviews linter settings from previous PRs and applies the unified linting rules to all `.ts` files in the src folder.
2) Corrects small things like returns of type `Promise<string> | never` to `Promise<string | never>`.
3) Makes tsc compiler settings in lib stricter, by disallowing `.js` files and not emitting transpiled Javascript if the tsc compiler encounters errors.
4) Also, the compiler now outputs declaration files. These are `.d.ts` files that reside next to transpiled `.js` files in the packages/lib/lib (build) folder, which can be used by other Typescript modules that use this module as a dependency (e.g. packages/cli). 
5) Note that point 3 implies that we now have different tsc compiler settings for sources and for …
=> Wrapping up the Ts port of lib, phases 1 and 2

.travis.yml, packages/cli/src/models/files/index.ts
This PR attempts to fix TravisCI integration tests' builds. Long story short, running `npm install` just after running `lerna bootstrap` did the trick. 
This issue may be related to how lerna manages `npm i` runs in a continuous integration environment (see: https://github.com/lerna/lerna/pull/1360#discussion_r179851072). Basically, it runs a `npm ci` instead of a `npm i`.
I also implemented a small fix related to a file import in `packages/cli` that was breaking `packages/vouching` tests.
=> Integration tests fix

packages/cli/package.json
Closes https://github.com/zeppelinos/zos/issues/518.
Just running a `chmod 755 ./lib/bin/zos-cli.js` after running `npm run compile-ts`. It seems that tsc doesn't keep file system permissions, as mentioned here: https://github.com/Microsoft/TypeScript/issues/16257#issuecomment-319604800
@facuspagnuolo, I noticed that `src/bin/errors.js` and `src/bin/program.js` have also execute permissions, but I don't see why. Any hints?
=> Make `lib/bin/zos-cli.js` executable after transpiling to ts

.travis.yml
Fix #549 (partially)
This PR makes a few modifications to .travis.yml, with the intention of shaving a few minutes of the CI tests:
1) Fewer lerna bootstraps are performed. 
~2) Use the apt addon to cache apt packages. I'm still not sure if this speeds up or slows down the tests, since Travis' performance is non-deterministic and seems to have it's own mood. Will have to experiment a bit.~
In total, the tests are run aprox. 10 minutes faster.
=> Speeds up Travis CI tests

packages/cli/src/models/files/ZosNetworkFile.ts, packages/cli/src/models/files/ZosPackageFile.ts, packages/cli/src/models/network/NetworkController.ts, packages/cli/src/scripts/publish.ts, packages/cli/src/scripts/status.ts, packages/cli/test/models/TestHelper.test.js, packages/cli/test/scripts/create.test.js, packages/cli/test/scripts/init.test.js, packages/cli/test/scripts/push.test.js, packages/cli/test/scripts/status.test.js, packages/cli/test/scripts/update.test.js
This PR removes some deprecated terminology related to the state of a zos project. Basically, all references to a `full project` and `lightweight project` were renamed in favor of  `published project` and `unpublished project`.
=> Remove lightweight terminology

.travis.yml
Fix #549 
Even though it looked cleaner to have separate stages for the tests, running only 2 stages (bootstrapping and testing) makes the whole test suite run at about half the time (23 mins vs 50 mins).
=> Run lib, cli, vouching, examples, and integration tests in parallel.

.travis.yml
Travis is not finding some dependencies when running some particular stages. I'm adding new installation steps for those stages in order to re-run `lerna bootstrap`. This should be considered a temporal solution, it increases the execution time of those stages in 10 minutes.
=> Force lerna bootstrap in some CI scenarios

packages/cli/package-lock.json, packages/docs/docs/docs/erc20_onboarding.md, packages/docs/docs/docs/linking.md, packages/docs/docs/docs/upgrading.md, packages/docs/docs/website/versioned_docs/version-2.0.0/erc20_onboarding.md, packages/docs/docs/website/versioned_docs/version-2.0.0/linking.md, packages/docs/docs/website/versioned_docs/version-2.0.0/upgrading.md, packages/lib/test/src/utils/Transactions.test.js
Fixes https://github.com/zeppelinos/zos/issues/562
We are telling the user to run `npx truffle console` to test their upgradeable contract. Therefore, if the user is running a Truffle 5 project, the steps we are telling them to reproduce won't work: we are using `at` which is now async.
=> Fix doc guides to support Truffle 5 environment

packages/cli/src/models/compiler/Compiler.ts
When compiling, if there is no local binary for truffle in node_modules, fall back to a global instance. Catch error 127 (file not found) and display a friendlier message.
This pull request is equivalent to #596, but against master instead of against release 2.1.0.
Disclaimer: I failed miserably in attempting to test it locally, since any attempts to run `zos` after installing from master throw `zos_lib_1.Contracts.setLocalBuildDir is not a function`. 
Fixes #579
=> Use global truffle for compiling (master)

packages/cli/src/models/network/NetworkController.ts, packages/cli/test/scripts/publish.test.js
After implementing #588 and while implementing the migration between zosversion 2 and zosversion 2.2, I noticed that all owned proxy contracts were being transferred from `ProxyAdmin` to `App`, and that's not the intended behaviour, as proxies should be always owned by the `ProxyAdmin`.
=> Avoid transferring proxies to `app` on publish

packages/lib/contracts/mocks/StorageMocks2.sol, packages/lib/contracts/mocks/StorageMocksForComparison.sol, packages/lib/src/validations/Layout.js, packages/lib/test/src/validations/Layout.test.js
Fixes two issues with storage layout checks:
1- Certain append operations were not being properly recognized, they were identified as insertions and caused false positives. This was found during the latest deployment of openzeppelin-eth, and added as a regression test. The problem was that the edition distance matrix always preferred a diagonal path with zero cost, even if this meant an accumulated cost higher than taking another paths. This is typically not an issue with levenshtein, since diagonal paths are always optimal, but here we break that invariant as we have free appends.
2- The algorithm was failing if either the initial or target contract had no storage whatsoever. Not only something different from a matrix was being returned, but also the cost of the first row of the matrix …
=> Fixes in storage layout checks

packages/lib/contracts/mocks/StorageMocks2.sol, packages/lib/contracts/mocks/StorageMocksForComparison.sol, packages/lib/src/validations/Layout.ts, packages/lib/test/src/validations/Layout.test.js
Port of #606 to master.
---
Fixes two issues with storage layout checks:
1- Certain append operations were not being properly recognized, they were identified as insertions and caused false positives. This was found during the latest deployment of openzeppelin-eth, and added as a regression test. The problem was that the edition distance matrix always preferred a diagonal path with zero cost, even if this meant an accumulated cost higher than taking another paths. This is typically not an issue with levenshtein, since diagonal paths are always optimal, but here we break that invariant as we have free appends.
2- The algorithm was failing if either the initial or target contract had no storage whatsoever. Not only something different from a matrix was being returned, but also the cost of …
=> Fixes in storage layout checks (master)

packages/cli/src/models/compiler/Compiler.ts
We were outputting the stdout and stderr from truffle compile twice. This PR fixes that.
=> Remove duplicated output from truffle compile

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/models/initializer/ConfigVariablesInitializer.ts, packages/cli/src/models/initializer/truffle/Truffle.ts, packages/lib/src/artifacts/Contracts.ts
This PR removes truffle resolver from CLI (which was being unused) which removes most of the truffle packages as a dependency, and upgrades truffle config to the latest version. It also picks up the `from` setting from truffle-config, which was being ignored and overridden by the default account.
=> Remove truffle resolver from CLI

packages/lib/package-lock.json, packages/lib/package.json, packages/lib/src/utils/Transactions.ts
Calls to estimateGas on geth fail if a gas parameter is provided which is lower than the required gas to execute the tx (but higher than the minimum of 21k). See https://github.com/ethereum/go-ethereum/issues/18973 for more info. Removing the gas parameter fixes this issue, and works on geth, parity, and ganache. Note that using a very low or very high gas value also works on geth and parity, but not on ganache.
=> Fix issue with gas estimation on geth

packages/cli/contracts/mocks/Boolean.sol, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/utils/input.ts, packages/cli/test/commands/create.test.js, packages/cli/test/scripts/create.test.js, packages/cli/test/utils/input.test.js, packages/lib/package-lock.json, packages/lib/package.json
Fix #558 
This PR solves the issue "Ability to pass false booleans via the cli" by:
1) Modifying input.ts so that incoming string values that are either "false" or "true" are converted into `false` and `true` literals respectively. Notice that this makes booleans the only type of values that do not exit as strings from input.ts. The file input.test.js is also modified to test for this change.
2) Adds a test to the create command, ensuring that a "false" argument does indeed get parsed into `false` instead of `true`.
3) Adds tests to the create script, with a new Booleans.sol contract, ensuring that calling the script with boolean literals produces the expected results.
This does not modify encodeCall in any way to maintain compatibility with Web3's encoder. If "false" is passed to …
=> Adds ability to receive false booleans via the cli

packages/lib/test/contracts/ProxyAdmin.test.js
Implemented @alcuadrado suggestions in `packages/lib/test/contracts/ProxyAdmin.test.js`.
=> Fix `ProxyAdmin` tests

packages/lib/package-lock.json, packages/lib/package.json
Updated `truffle-flattener` version to `1.2.12`, which includes https://github.com/nomiclabs/truffle-flattener/pull/36 :raised_hands: .
=> Update truffle-flattener version

packages/cli/src/models/compiler/Compiler.ts
Fixes #644, fixes #641. I moved both `console.log` and `console.error` outside the if/else clauses.
=> Log `truffle compile` output outside if/else

packages/lib/src/artifacts/ZWeb3.ts
Fixes https://github.com/zeppelinos/zos/issues/647. The problem was that while working with mainnet/any testnet, `ZWeb3#isGanacheNode` was trying to access to the `length` attribute of a `null` value, which made the cli crash, for example, when calling `ZWeb3#awaitConfirmations` in `zosversion` migration.
=> Fix in ZWeb3#ganacheNode return statement

packages/lib/src/artifacts/ZWeb3.ts
Fixes https://github.com/zeppelinos/zos/issues/645.
=> Get accounts from `web3.eth` in ZWeb3 instead of getting them from `web3.eth.personal`.

packages/cli/src/models/Verifier.ts
Related to https://github.com/zeppelinos/zos/issues/636. Minor fix in etherscan mainnet url found while manually testing zos.
=> Fix etherscan mainnet url

packages/docs/docs/docs/deploying.md, packages/docs/docs/docs/linking.md, packages/docs/docs/docs/publish.md, packages/docs/docs/docs/upgrading.md, packages/docs/docs/docs/zos_lib.md
Fix #639 
Part of #635 
This PR updates the guides in the quickstart section of the docs to use `npx zos` so that we make sure that the user is using ZeppelinOS 2.1, pins Truffle to 4.1.15, rollsback all example contracts to Solidity 0.4.24, and pins openzeppelin-eth to 2.0.2 (which is the last version that had Solidity 0.4.24 contracts).
=> Update the quickstart section guides to work with zOS 2.1.

packages/cli/package.json, packages/cli/scripts/copy-files.sh
When running `zos init myProject` in a directory that has not yet been initialized by truffle, the following error is thrown:
```
ENOENT: no such file or directory, copyfile '/home/user/myProject/node_modules/zos/lib/models/initializer/truffle/blueprint.truffle.js' -> '/home/user/myProject/truffle-config.js'
```
The truffle.js blueprint does not make it to lib, because the Typescript compiler simply ignores it.
This PR adds a copy-files.sh script that simply copies the file into the lib folder.
=> Fix blueprint.truffle.js not being available in cli/lib output

packages/docs/README.md, packages/docs/package-lock.json, packages/docs/package.json, packages/docs/scripts/bump-docs.js, packages/docs/scripts/generators.js
Fixes #670.
I've implemented some minor changes to the `bump-script.js` file so it can receive a particular branch as an argument.
Specifying an already released version:
```sh
foo@bar:~$: npm run bump-docs 1.2.0
```
Specifying a version and a branch:
```sh
foo@bar:~$: npm run bump-docs 1.2.0 a_remote_branch
```
=> Allow bump script to receive a branch as argument

packages/cli/src/commands/create.ts, packages/cli/src/commands/publish.ts, packages/cli/src/commands/set-admin.ts, packages/cli/src/commands/update.ts, packages/cli/src/models/files/ZosNetworkFile.ts, packages/cli/src/models/files/ZosPackageFile.ts, packages/cli/test/commands/share.js
The `zosversion` check has been changed in order to check it in the `zos.network.json` file rather than in the `zos.json` file. This means that we are going to prompt the migration question for each network independently instead of checking it once and then migrate without asking on the remaining networks.
=> Prompt migration question for each network independently

packages/docs/docs/docs/testing.md
=> Added a note on calling overloaded functions with Truffle 4 and 5.

packages/lib/src/artifacts/ZWeb3.ts, packages/lib/test/src/artifacts/ZWeb3.test.js
Fixes #735.
As discussed offline with @spalladino, we are now initializing `ZWeb3#web3` without a provider instead of throwing an error.
=> Initialize ZWeb3 without a provider

packages/lib/contracts/application/App.sol, packages/lib/contracts/application/ImplementationDirectory.sol, packages/lib/contracts/application/Package.sol, packages/lib/contracts/mocks/DeprecatedApp.sol, packages/lib/contracts/openzeppelin-solidity/ownership/Ownable.sol, packages/lib/contracts/openzeppelin-solidity/utils/Address.sol, packages/lib/contracts/upgradeability/ProxyAdmin.sol, packages/lib/contracts/upgradeability/UpgradeabilityProxy.sol, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/test/src/application/App.test.js
This PR removes openzeppelin as a dependency from `zos-lib`, to allow for client projects to use whichever version of OpenZeppelin they prefer. Given that we were using only 2 contracts, we are currently manually copying them into the project. See [this thread](https://forum.zeppelin.solutions/t/zeppelinos-and-openzeppelin-compatible-versions/311) for more info.
=> Remove openzeppelin-solidity as a dependency

packages/cli/src/models/compiler/Compiler.ts
Use execFile to provide path to file and options separately, instead of using plain exec with a manually built command string.
Fixes #708
=> Handle spaces in project path

packages/cli/src/commands/push.ts, packages/cli/src/models/dependency/Dependency.ts, packages/cli/src/models/files/ZosNetworkFile.ts, packages/cli/src/models/network/Session.ts, packages/cli/src/utils/prompt.ts, packages/cli/test/commands/add.test.js, packages/cli/test/commands/bump.test.js, packages/cli/test/commands/check.test.js, packages/cli/test/commands/create.test.js, packages/cli/test/commands/freeze.test.js, packages/cli/test/commands/init.test.js, packages/cli/test/commands/link.test.js, packages/cli/test/commands/publish.test.js, packages/cli/test/commands/push.test.js, packages/cli/test/commands/remove.test.js, packages/cli/test/commands/session.test.js, packages/cli/test/commands/setAdmin.test.js, packages/cli/test/commands/status.test.js, packages/cli/test/commands/unlink.test.js, packages/cli/test/commands/update.test.js, packages/cli/test/commands/verify.test.js, packages/cli/test/mocks/networks/network-with-stdlibs.zos.test.json, packages/cli/test/models/Dependency.test.js, packages/cli/test/models/ZosNetworkFile.test.js, packages/cli/test/scripts/session.test.js, tslint.json
Fixes #707, fixes #716.
This PR includes:
- Automatic deployment of dependencies if working with `ganache`
- Prompt to deploy dependencies if necessary
- Save last network used for using it as default for next time
EDIT: I also refactored a bit the commands tests. Sorry for doing  this here PR :eyes:
=> interactive push (first part)

packages/cli/contracts/mocks/ImplV1.sol, packages/cli/contracts/mocks/ImplV2.sol, packages/cli/src/models/initializer/truffle/Truffle.ts, packages/cli/src/models/local/LocalController.ts, packages/cli/test/scripts/add.test.js
Addresses #754
This fixes the issue where `zos add --all` adds non-project and library contracts. I identified project contracts by recursing through the contracts directory and aggregating an array of contract names stripped of file extensions. We then check against that array of project contracts while going through the built contracts to add and only add those that are found in the project. 
Libraries are excluded by checking the through the contracts' compiled JSON interface, this may be fragile as it appeared on first glance that the `contractKind` always appears on the second element of the `contractData.ast.nodes` array - if that's not the case it would be simple to refactor this to iteratively check for that value.
=> zos add --all should only add non-library project contracts

packages/cli/src/models/network/NetworkController.ts, packages/cli/test/scripts/create.test.js
I wanted to look at the `create2` stuff a bit more and this seemed like a good issue(#774) to dive into it with. Added a check in `NetworkController.createProxy` to ensure the deployment address isn't occupied prior to calling `createProxyWithSalt`. Added a case to `create.test.js` covering this change.
=> feature/check address prior running create2 #774

.circleci/config.yml
Lib and CLI caches were calculated based on the checksum of the package json,
yet they included the result of the build process. This caused changes on the
package code to be lost if the package.json did not change.
This fix adds a new cache to host the result of the build process, that
depends exclusively on the revision being built.
=> Fix circleci caches

packages/cli/src/commands/set-admin.ts, packages/cli/src/models/network/NetworkController.ts, packages/cli/src/scripts/set-admin.ts, packages/cli/test/commands/setAdmin.test.js, packages/cli/test/scripts/set-admin.test.js, packages/lib/src/project/AppProject.ts, packages/lib/src/project/ProxyAdminProject.ts, packages/lib/src/proxy/ProxyAdmin.ts, packages/lib/test/src/ProxyAdmin.test.js, packages/lib/test/src/project/AdminProxy.behaviour.js, packages/lib/test/src/project/AppProject.test.js, packages/lib/test/src/project/ProxyAdminProject.test.js, packages/lib/test/src/project/ProxyProject.behaviour.js
* Adds required functionality to a `set-admin` command in the following way:
`zos set-admin <new-proxy-admin-address>`
* Use interactive check to prevent admin address input errors.
* Adds tests to support required changes.
=> Adds ability to change owner of a proxy admin to set-admin command

examples/creating-instances-from-solidity/index.js, packages/cli/test/models/TestHelper.test.js, packages/lib/src/artifacts/Contract.ts, packages/lib/test/src/artifacts/Contract.test.js
Function `Contract#at` was modifying the current instance instead of creating a new one. This caused two invocations to `at` on the same contract with different addresses to end up yielding the same instance.
Fixes #784
=> Fix Contract#at to create a clone of the current instance

examples/lib-simple/README.md
This pull request adds lacking README.md file to the lib-simple example project.
Part of #769
=> Add README to lib-simple example project #769

packages/lib/src/project/AppProject.ts, packages/lib/src/project/ProxyAdminProject.ts, packages/lib/src/project/mixin/ProxyAdminProjectMixin.ts, packages/lib/src/utils/Mixin.ts
The goal of the PR is to eliminate code duplication at ProxyAdminProject and AppProject classes as well as introduce and showcase TypeScript Mixins usage in the project.
Notes on TypeScript Mixins
TypeScripts Mixins is a relatively new feature with no official or community consensus on usage or established library. It is under development and presents certain challenges. Mixins are great for development but should be used with caution. [Official documentation](https://www.typescriptlang.org/docs/handbook/mixins.html) is outdated but there is [PR](https://github.com/Microsoft/TypeScript/pull/13743) introducing a new approach.
Regarding ZOS I struggled with mixin abstract classes. Generally speaking [it is not possible](https://github.com/Microsoft/TypeScript/issues/25606) to mixin abstract …
=> Eliminates ProxyAdmin code duplication in ProxyAdminProject and AppProject using TypeScript Mixins

packages/cli/contracts/mocks/ERC20Fake.sol, packages/cli/src/commands/balance.ts, packages/cli/src/commands/index.ts, packages/cli/src/models/network/TransactionController.ts, packages/cli/src/scripts/balance.ts, packages/cli/src/scripts/index.ts, packages/cli/src/scripts/interfaces.ts, packages/cli/src/scripts/transfer.ts, packages/cli/src/utils/constants.ts, packages/cli/src/utils/units.ts, packages/cli/test/commands/balance.test.js, packages/cli/test/commands/share.js, packages/cli/test/scripts/balance.test.js, packages/cli/test/utils/units.test.js, packages/lib/src/artifacts/ZWeb3.ts, packages/lib/test/src/artifacts/ZWeb3.test.js, packages/lib/test/src/utils/Transactions.test.js
Fixes #828, fixes #829.
Started implementing both interactive command and script to get the balance of an account on a specified network, or to get the balance in tokens if an ERC20 address is specified.
Example usage:
Still have to add some tests, and also decide what to do with the ERC20 `abi` that I included in a new `utils/constants.ts`, which I believe it's mandatory to have in the project to query both token balance and symbol.
~_Message for the reviewer: I branched from `feature/transfer-command` and squashed all the commits implemented on it for making the review easier. You should review all commits after `f3f0b76` (included). After merging https://github.com/zeppelinos/zos/pull/823, we can remove that squashed commit_.~
=> Balance command

packages/cli/src/commands/create2.ts, packages/cli/src/models/TestHelper.ts, packages/cli/src/models/dependency/Dependency.ts, packages/cli/src/models/initializer/ConfigVariablesInitializer.ts, packages/cli/src/models/local/LocalController.ts, packages/cli/src/models/network/NetworkController.ts, packages/cli/src/models/network/ProjectDeployer.ts, packages/cli/src/models/network/TransactionController.ts, packages/cli/src/models/status/StatusChecker.ts, packages/cli/src/scripts/interfaces.ts, packages/lib/src/application/App.ts, packages/lib/src/application/ImplementationDirectory.ts, packages/lib/src/application/Package.ts, packages/lib/src/artifacts/ZWeb3.ts, packages/lib/src/helpers/copyContract.ts, packages/lib/src/index.ts, packages/lib/src/project/AppProject.ts, packages/lib/src/project/BasePackageProject.ts, packages/lib/src/project/BaseSimpleProject.ts, packages/lib/src/project/PackageProject.ts, packages/lib/src/project/ProxyAdminProject.ts, packages/lib/src/project/SimpleProject.ts, packages/lib/src/proxy/Proxy.ts, packages/lib/src/proxy/ProxyAdmin.ts, packages/lib/src/proxy/ProxyFactory.ts, packages/lib/src/utils/Migrator.ts, packages/lib/src/utils/Transactions.ts
* The PR adds `set-admin` owner check in order to provide more meaningful messaging, and prevents sending failing transactions.
* It also introduce `TxParams` interface across `lib` and `cli` project for consistent typing. 
* Refactors `ConfigVariablesInitializer` to ES6 class.
=> Fix set-admin owner check

packages/cli/src/commands/create.ts, packages/cli/src/models/files/ZosNetworkFile.ts, packages/cli/src/models/network/NetworkController.ts, packages/cli/src/prompts/prompt.ts, packages/cli/src/scripts/create.ts, packages/cli/src/scripts/interfaces.ts, packages/cli/test/commands/create.test.js, packages/cli/test/scripts/create.test.js, packages/cli/test/scripts/update.test.js, packages/lib/contracts/mocks/DummyImplementation.sol, packages/lib/contracts/upgradeability/ProxyFactory.sol, packages/lib/src/index.ts, packages/lib/src/project/AppProject.ts, packages/lib/src/project/BaseSimpleProject.ts, packages/lib/src/proxy/MinimalProxy.ts, packages/lib/src/proxy/ProxyFactory.ts, packages/lib/test/src/ProxyFactory.test.js, packages/lib/test/src/project/ProxyProject.behaviour.js
Adds PR for [EIP 1167 minimal](http://eips.ethereum.org/EIPS/eip-1167) non-upgradeable proxies. A user may now use the `--minimal` flag on the `create` command, which spawns a minimal proxy instead of a regular one. Under the hood, it spawns a `ProxyFactory` which is used to create and initialize the non-upgradeable proxies in a single tx.
=> Minimal proxies

packages/lib/package-lock.json, packages/lib/package.json, packages/lib/src/helpers/encodeCall.ts, packages/lib/test/contracts/application/App.test.js, packages/lib/test/contracts/application/ImplementationDirectory.test.js, packages/lib/test/src/project/ProxyAdminProject.test.js, packages/lib/test/src/project/SimpleProject.test.js, packages/lib/test/src/validations/Layout.test.js, packages/lib/test/src/validations/Validations.test.js
I removed some references to `lodash` (which is not installed in our repo) while porting some features to `release/2.3` in https://github.com/zeppelinos/zos/pull/876.
It seems that `tsc` is not complaining because other `zos` dependencies depend on `lodash`, but I'm removing it as this may lead to future errors.
=> Remove references to `lodash`

packages/cli/src/bin/zos-cli.ts
Fixes https://github.com/zeppelinos/zos/issues/868 for `release/2.3` branch.
=> [release/2.3] Don't look for root dir on `zos unpack`

packages/cli/src/prompts/prompt.ts, packages/cli/test/prompts/prompt.test.js
Fixes bug on `source === 'fromLocal'` branch, and adds tests.
Fixes #884
=> Fix prompt#contractsList with source fromLocal

packages/cli/src/commands/publish.ts, packages/cli/src/prompts/prompt.ts, packages/cli/test/prompts/prompt.test.js, packages/cli/test/setup.js
Implements #874;
Would help to implement tools like Solidity Hot Loader which have to run all commands in non interactive mode.
You can set `zos` in non interactive mode by setting either `ZOS_NON_INTERACTIVE` env variable or `DEBIAN_FRONTEND` to `noninteractive`.
@jcarpanelli can you take a look at line 59 and 70 in prompt.test.js? These two test have the same code but different names. Pretty sure that is not what intended.
=> Add interactivity env

packages/cli/src/models/network/NetworkController.ts, packages/cli/test/scripts/push.test.js
Outputs "All logic contracts are up to date" if no contracts were pushed.
Needs to be merged back or cherry-picked into master.
Fixes #870
=> Output a message if no contracts were pushed

packages/cli/contracts/mocks/ImplV1Clash.sol, packages/cli/src/models/network/NetworkController.ts, packages/cli/test/helpers/captureLogs.js, packages/cli/test/scripts/push.test.js, packages/lib/src/artifacts/BuildArtifacts.ts, packages/lib/src/utils/ContractAST.ts, packages/lib/src/validations/index.ts
If there are two contracts with the same name on the same project, truffle will compile them to the same artifact (ContractName.json), overwriting one of them. This causes some validations to fail, such as storage validations, since they expect a set of AST nodes that is not found due to the overwritten artifact. It also yields false negatives in other validations, such as no-delegatecalls, since it looks for all parent contracts, but it could end up loading an incorrect one (since the right one was overwritten).
This change walks through the set of ancestors of a given contract, and checks that the referenced AST ID for each of them is present among the set of imported artifacts. While this was doable by just trying to load the nodes that corresponded to the linearized base contracts, …
=> Check duplicated artifact names

packages/cli/scripts/test.sh, packages/lib/contracts/mocks/MockStandaloneERC721.sol, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/scripts/test.sh, packages/lib/src/utils/Transactions.ts, packages/lib/test/src/utils/Transactions.test.js
Recent versions of ganache (>= 6.4.0) return too low values for gas estimation, causing some transactions to fail.
- Use block gas limit for estimates when on ganache
- Update to ganache 6.4 to reproduce the issue
- Add a sample standalone erc721 to reproduce the issue
- Refactor sinon.restore calls in transaction tests
Fixes #846 
Related to https://github.com/trufflesuite/ganache-core/issues/428
=> Use block gas limit for transactions on ganache

packages/cli/src/models/network/NetworkController.ts, packages/cli/src/prompts/prompt.ts, packages/lib/src/artifacts/Contract.ts, packages/lib/test/src/artifacts/Contract.test.js
Fixes #900. Now we are picking contract functions from the `ABI` and we are only using the `AST` to pick functions modifiers.
=> Pick contract functions always from ABI instead of using AST.

packages/cli/src/models/network/NetworkController.ts, packages/cli/src/prompts/prompt.ts, packages/lib/src/artifacts/Contract.ts, packages/lib/test/src/artifacts/Contract.test.js
Cherry-picked from  `fix/pick-contracts-from-abi-and-not-from-ast`. Fixes #900.
=> [release 2.3] Pick contract functions always from ABI instead of using AST.

packages/lib/src/artifacts/Contracts.ts
Fixes https://github.com/zeppelinos/zos/issues/927. The main problem was that the previous regexp was not precise enough to cover some edge (well, not precisely edge) cases  if having a project directory path such as: `foo/bar/bazcontracts`, or anything with a `contracts` at the end of the directory name.
Now, we are using `path#dirname` instead (thanks @ylv-io!!)
If approved, I will add this to the `release/2.3` branch.
=> Fix directory path replacement

packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts, packages/cli/test/models/compiler/solidity/SolidityContractsCompiler.test.js, packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js
Removes absolute paths in artifacts, to make sure they are portable between workstations. Fixes any issues with isLocalContract check, and generates metadata independent of the computer where it was compiled (important for EXTCODEHASH checks).
Fixes #933
=> Use relative paths in compiled artifacts

packages/lib/package-lock.json, packages/lib/package.json, packages/lib/src/utils/Bytecode.ts, packages/lib/test/src/utils/Bytecode.test.js
Since Solidity 0.5.2, the swarm hash is included along with the compiler version, CBOR encoded at the end of the runtime bytecode. This handles both metadata versions and removes the swarm hash from both of them.
Fixes #844
=> Handles swarm hash metadata for solidity 0.5.2

packages/cli/src/models/compiler/Compiler.ts
Running zos compile in a project without zos.json would create a zos.json file without name or version, which caused the project to crash later.
There were two options to fix this:
1- Refuse to compile before init
2- Compile anyway without persisting compiler flags
I went with (2), to make it easier to use zos as a standalone compiler, without needing to init a project wherever the user wants to run it.
Fixes #955 
_Needs rebase after #957 is merged_
=> Do not write invalid zos.json if compiling before init

packages/cli/mocks/mock-stdlib-with-deps/node_modules/mock-dep/contracts/GreeterDep.sol, packages/cli/mocks/mock-stdlib-with-deps/node_modules/mock-dep/contracts/subdep/GreeterSubdep.sol, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/models/compiler/solidity/ResolverEngineGatherer.ts, packages/cli/src/models/files/ZosPackageFile.ts, packages/cli/test/mocks/mock-stdlib with spaces/contracts/GreeterImpl.sol, packages/cli/test/mocks/mock-stdlib with spaces/contracts/GreeterLib.sol, packages/cli/test/mocks/mock-stdlib with spaces/package.json, packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js
A project in a path with spaces would fail to lookup any contracts or imports. The issue has been reported in the resolver-engine repo (https://github.com/Crypto-Punkers/resolver-engine/issues/176) and patched here.
This PR also includes a commit to handle empty nodes in the zos.json config file, as they were causing the CI to fail when testing zepkit integration (kudos @ylv-io for getting that suite working!).
Fixes #951
Fixes #952
_Needs rebase after #957 is merged_
=> Handle paths with spaces when compiling artifacts

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/call.ts, packages/cli/src/commands/create.ts, packages/cli/src/commands/send-tx.ts, packages/cli/src/commands/update.ts, packages/cli/src/prompts/method-params.ts, packages/cli/src/prompts/prompt.ts, packages/cli/src/utils/input.ts, packages/cli/test/prompts/prompt.test.js, packages/cli/test/utils/input.test.js
Parses arguments to call a method (such as in the call, send-tx, update, or create commands) according to the argument type. 
In order to accepts arrays with elements with and without quotes (so something simple like `foo,bar` would work, without requiring the user to input `["foo","bar"]`), I wrote a simple parser by hand. Please take a good look at it.
I'm also merging the PR onto `release/2.4` directly to publish a new RC, but I'd appreciate if either @jcarpanelli or @ylv-io could review this PR after merged in case something slipped through.
=> Improve parsing of interactive args

packages/lib/package-lock.json, packages/lib/package.json, packages/lib/src/utils/Logger.ts, packages/lib/test/setup.js, packages/lib/test/src/utils/Logger.test.js
Fixes https://github.com/zeppelinos/zos/issues/979.
This PR also:
- Adds tests for the new logger.
- Updates `spinnies` to latest version, in which non-spinnable text prefix has been removed and the default terminal color has been set as default.
=> Fix error when printing errors in verbose mode

packages/cli/src/utils/input.ts, packages/cli/test/utils/input.test.js
Fixes parsing of integer and boolean arrays in arguments for interactive commands. Also adds much-needed tests. Built upon #976.
=> Fix parsing of integer arrays

packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts, packages/lib/src/artifacts/Contracts.ts, packages/lib/test/src/artifacts/Contracts.test.js
Resolves the source and build folder **after** the process.cwd has taken place in zos-cli. Also, removes the usage of `zos-lib/FileSystem#createDirPath` which was not working properly, in favor of vanilla fs and fs-extra.
Fixes #984
=> Fix compile command run on subfolder

packages/cli/src/models/compiler/solidity/CompilerProvider.ts, packages/cli/src/models/compiler/solidity/SolidityContractsCompiler.ts
As seen offline together with @spalladino, the compiler was printing some `undefined` messages on verbose mode. this PR fixes that.
=> Fix compiler logs

packages/cli/src/models/compiler/Compiler.ts, packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts, packages/cli/test/models/compiler/Compiler.test.js
This ensures that two subsequent compiles are done with the same version, even if a new solc is released inbetween them.
Fixes #1004.
=> Save compiler version resolved by compiler in zos.json

packages/cli/src/prompts/method-params.ts
=> Use selector instead of name for identifying a method

packages/cli/src/@types/solc-wrapper.d.ts, packages/cli/src/commands/compile.ts, packages/cli/src/models/compiler/solidity/CompilerProvider.ts, packages/cli/src/models/compiler/solidity/SolidityContractsCompiler.ts, packages/cli/src/models/files/ZosPackageFile.ts, packages/cli/test/commands/compile.test.js
Fixed typings in solc module, and fixed error `The "runs" setting must be an unsigned number` when enabling optimizer via command line.
Fixes #1007
=> Compiler optimizer runs should be an integer

packages/cli/src/prompts/method-params.ts, packages/cli/src/utils/input.ts, packages/lib/src/artifacts/ZWeb3.ts
Use the arg type and inquirer validate callback to check that the user input is correct. If not, we show an example on how to input the value.
Fixes #999
=> Validate method args in interactive prompt

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/commands/compile.ts, packages/cli/src/models/compiler/Compiler.ts, packages/cli/src/models/files/ZosPackageFile.ts, packages/cli/test/commands/compile.test.js
- Allow to disable the optimizer via --optimizer=off option (was not possible to do before)
- Properly merge options from command line and defaults from zos.json (object assign replaced by lodash merge, it was not working ok for the optimizer which was a nested object)
- Handle undefined value for runs when loading it from zos.json
=> Fix issues with compiler optimizer settings

packages/docs/docs/docs/writing_contracts.md
Related to https://forum.zeppelin.solutions/t/is-it-ok-to-define-constants-in-upgradable-contracts-with-zeppelinos/892/2
=> Constants still work the normal way with zos

packages/cli/src/commands/set-admin.ts, packages/cli/src/commands/update.ts, packages/cli/src/utils/events.ts, packages/cli/test/utils/events.test.js
Related to #1021. Doesn't solve it, but Now we can remove the `bug` flag :stuck_out_tongue:
=> Avoid showing external contract emitted events

packages/cli/mocks/mock-project-with-root-imports/README.md, packages/cli/mocks/mock-project-with-root-imports/contracts/subfolder/GreeterImpl.sol, packages/cli/mocks/mock-project-with-root-imports/contracts/subfolder/GreeterLib.sol, packages/cli/mocks/mock-project-with-root-imports/contracts/subfolder/GreeterLib2.sol, packages/cli/mocks/mock-project-with-root-imports/contracts/subfolder/GreeterLib3.sol, packages/cli/mocks/mock-project-with-root-imports/zos.json, packages/cli/src/models/compiler/solidity/ResolverEngineGatherer.ts, packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js
Support the syntax `import "contracts/Folder/C2.sol"` in a contract `contracts/Folder/C1.sol`.
Fixes #1024
=> Handle relative imports from project root in compiler

packages/docs/docs/docs/writing_contracts.md
Building on top of https://github.com/zeppelinos/zos/pull/1036, I added a link to the relevant part of the Solidity docs, for reference.
=> Add link to Solidity docs

packages/cli/src/models/compiler/Compiler.ts
Fixes error `Cannot read property version of undefined` when compiling and there are no contracts at all.
=> Fix compiler error when no contracts found

examples/lib-complex/package-lock.json, packages/cli/package-lock.json, packages/cli/package.json, packages/lib/package-lock.json, tests/cli/workdir/package-lock.json
Fixes #1046. While making some tests with @spalladino, we noticed that `yarn` was installing an older version of `@resolver-engine/core` (v0.2.1) which has a different project structure and was causing problems. I've explicitly added the dependency in the `cli`'s `package.json`.
Last but not least, I also pinned the `zos-lib` version.
=> Explicitly specify `@resolver-engine/core` version

packages/lib/package-lock.json, packages/lib/package.json
Upgraded `spinnies` to  v0.4.3, which supports Unicode characters in some Windows terminals.
=> Upgrade spinner manager to v0.4.3

packages/cli/src/commands/compile.ts, packages/cli/src/models/compiler/Compiler.ts, packages/cli/test/commands/compile.test.js, packages/cli/test/models/compiler/Compiler.test.js
=> Rename compiler manager to openzeppelin

packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts, packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js
=> Preserve deployment info on compile

package-lock.json, package.json, packages/cli/src/models/dependency/Dependency.ts, packages/cli/test/models/Dependency.test.js, packages/cli/test/scripts/unlink.test.js, packages/lib/src/artifacts/Contracts.ts, packages/lib/test/src/artifacts/Contracts.test.js
Change lookup in both Dependency and Contracts classes. Instead of looking for just node_modules in the current folder, it uses require.resolve (relative to the current workdir) to look for the dependency.
Fixes #1076
=> Use require.resolve to lookup contracts in deps

packages/cli/src/models/network/NetworkController.ts, packages/cli/test/setup.js, packages/lib/src/project/ProxyAdminProject.ts, packages/lib/src/project/SimpleProject.ts, packages/lib/src/utils/Logger.ts, packages/lib/test/setup.js, packages/lib/test/src/utils/Logger.test.js
When calling Loggy.success with a non-existing key, the reference would not be found, and the call to path.basename in Loggy._log would fail (since its parameter was null). This commit:
- Catches any exceptions in _log, and displays an error (allowing to continue)
- Adds a testing mode to the logger, which is silent but executes logic, and throws an exception upon issues (only to be used in the CLI and lib tests)
- Fixes incorrect or missing keys in calls to the logger
_Note: we should cherry pick this one onto 2.4_
=> Handle incorrect keys to loggy

packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts, packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js
=> Do not fail if contracts folder is missing

packages/lib/package.json
We are importing `web3-utils` in `Addresses.ts` in lib, and we don't have the package required in the `package.json`. Instead, we're relying in it being installed as part of web3.
This PR is an attempt to fix 1087.
=> Explicitly require web3-utils

packages/lib/src/project/BasePackageProject.ts
Add missing parameters to the `onVerbose` call. We definitely need to add types to Logger.ts!
=> Fix verbose logging in base package project

.circleci/config.yml, package-lock.json, package.json, packages/cli/changelog.md, packages/cli/package-lock.json, packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts, packages/cli/src/models/dependency/Dependency.ts, packages/cli/src/models/network/NetworkController.ts, packages/cli/test/models/Dependency.test.js, packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js, packages/cli/test/scripts/unlink.test.js, packages/cli/test/setup.js, packages/lib/changelog.md, packages/lib/src/artifacts/Contracts.ts, packages/lib/src/project/ProxyAdminProject.ts, packages/lib/src/project/SimpleProject.ts, packages/lib/src/utils/Logger.ts, packages/lib/test/setup.js, packages/lib/test/src/artifacts/Contracts.test.js, packages/lib/test/src/utils/Logger.test.js
Cherry picking fixes from master to 2.4 for a 2.4.2 release.
=> Rebase master for 2.4.2

packages/cli/src/commands/set-admin.ts
Fixes https://github.com/zeppelinos/zos/issues/1041. Removed unnecessary line breaks in the `set-admin` command description that made it look inconsistent compared to the other command descriptions when running `oz --help`.
=> Fix set-admin command description format

packages/cli/src/commands/push.ts, packages/cli/src/commands/set-admin.ts, packages/cli/test/commands/push.test.js, packages/cli/test/commands/setAdmin.test.js
Flag -f was already being used for --from, but was overwritten by both push and set-admin as force. Now --from is the only accepted meaning.
Fixes #1052
=> Remove repeated flag -f from push and set-admin

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/utils/async.ts, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/src/utils/Semver.ts
Removes `lodash.isarray` (which is deprecated) from both packages, and gets rid of this warning when installing the sdk:
=> Use Array.isArray instead of lodash.isarray

packages/cli/src/bin/program.ts
Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1120. Seems that the commander `alias` won't work as expected for the `openzeppelin` command. I added an `oz` into the command name so it looks exactly as how commander shows aliases:
`zos upgrade --help` for reference:
I `npm pack`ed it and works as expected!
=> Show `oz` alias in openzeppelin cmd description

README.md, packages/cli/src/commands/link.ts, packages/cli/src/interface/ValidationLogger.ts, packages/cli/src/models/files/ManifestVersion.ts, packages/cli/src/models/local/KitController.ts
Note that the default will not properly work until we rename and publish `openzeppelin-eth` as `@openzeppelin/contracts-ethereum-package`.
=> Fix docsite links and ethereum package reference in link command

packages/cli/src/models/dependency/Dependency.ts, packages/cli/test/models/Dependency.test.js
=> Handle packages from organizations on link

packages/cli/src/commands/init.ts, packages/cli/src/prompts/prompt.ts, packages/cli/src/prompts/validators.ts
Validates that name is not empty, and that version is semver compatible. Only on interactive command.
Fixes #1142
=> Validate init params

packages/cli/src/commands/accounts.ts, packages/cli/src/commands/index.ts, packages/cli/src/models/dependency/Dependency.ts, packages/cli/src/models/network/NetworkController.ts, packages/cli/src/prompts/prompt.ts, packages/cli/src/scripts/accounts.ts, packages/cli/src/scripts/index.ts, packages/cli/test/commands/accounts.test.js, packages/cli/test/commands/share.js, packages/cli/test/scripts/accounts.test.js
I had this in my `git stash` for a while... Just committed it so you can take care of it while I'm on vacations :slightly_smiling_face:  
Fixes #967?
*Note:* I wouldn't merge this feature for `v2.5.0`.
=> Implement `accounts` command

packages/docs/modules/ROOT/pages/configuration.adoc
Having a backtick next to a letter at the end of a word will not render it properly it seems, so I've removed anything post-backtick in such cases.
=> Some typos IRT formatting of inline code

packages/docs/modules/ROOT/pages/linking.adoc
I fixed some typos, and also remove versions from the eth package installation line. It didn't work for me and specific versions tend to go out of date in docs very quickly, so without it it goes smoothly. Also added error messages to require statements, linter was complaining, hope that's fine.
=> Typo fixes and require error messages

packages/cli/src/models/local/KitController.ts
Unpacking the starter-kit-gsn yielded an `stderr maxBuffer length exceeded` error due to the verbosity of npm install. This increases the default maxbuffer 100x from its default of 1024 ** 2.
=> Increase post unpack buffer

examples/cli-create2/package-lock.json, examples/cli-create2/package.json, examples/first-project/package.json, examples/lib-complex/package-lock.json, packages/cli/package-lock.json, packages/cli/package.json, packages/lib/package-lock.json, packages/lib/package.json, tests/cli/workdir/package-lock.json
Bumps web3 version to 1.2.1. This version has better node 12 support, and removes the problems with the .git folder from frozeman's websocket package. However, it introduces another issue: gulp being installed as a dependency. This has already been reported and may be fixed on a subsequent release.
=> Bump web3 version

packages/cli/src/models/local/KitController.ts, packages/cli/src/scripts/unpack.ts, packages/cli/test/scripts/unpack.test.js
Supports specifying a specific branch when running oz unpack using the syntax `oz unpack org/repo#branch`. This allows picking a non-stable branch for unpacking a box.
=> Allow specifying a branch on unpack command

tests/kits/test/src/integration.test.js
CI builds fail due to CRA warning caused by third party dependencies. We should ignore CRA warning for the purpose of integration tests.
=> Allow CRA builds with warnings

packages/docs/modules/ROOT/pages/zos-lib.adoc
Update contract names to MyContract_v0 and MyContract_v1 to match the names used in `index.js` in the documentation and the example project: https://github.com/OpenZeppelin/openzeppelin-sdk/tree/master/examples/lib-simple
Found when answering in the forum: https://forum.openzeppelin.com/t/how-to-deploy-upgradable-contracts-on-the-eth-chain-by-use-javascript/1152/2
=> Update zos-lib.adoc to update contract names to MyContract_v0 and MyContract_v1

packages/cli/src/interface/ValidationLogger.ts
Update documentation links as were resulting in page not found.
Updated links:
https://docs.openzeppelin.com/sdk/2.5/writing-contracts#potentially-unsafe-operations
https://docs.openzeppelin.com/sdk/2.5/writing-contracts#avoid-initial-values-in-field-declarations
https://docs.openzeppelin.com/sdk/2.5/writing-contracts#initializers
https://docs.openzeppelin.com/sdk/2.5/writing-contracts#modifying-your-contracts
Current warnings show invalid links
```
$ npx oz create
Nothing to compile, all contracts are up to date.
? Pick a contract to instantiate ABNMarket
? Pick a network development
✓ Added contract ABNMarket
✓ Deploying @openzeppelin/contracts-ethereum-package dependency to network dev-1566901042319
- Contract ABNMarket has an explicit constructor. Change it to an initializer function. …
```
=> Update documentation links in ValidationLogger.ts

packages/docs/modules/ROOT/pages/first.adoc
OpenZeppelin SDK now supports node 12 since 2.5.2
https://forum.openzeppelin.com/t/openzeppelin-sdk-2-5-2-with-node-12-support/1110
Remove note about not using node 12
=> Update first.adoc as OpenZeppelin supports node 12

packages/docs/modules/ROOT/pages/interacting.adoc
Remove note on installing web3 only with node 10 and remove specific version of web3 to install
web3.js now supports node 12: https://github.com/ethereum/web3.js/releases/tag/v1.2.1
=> Update interacting.adoc as web3 now supports node 12

packages/docs/modules/ROOT/pages/interacting.adoc
Suggested by @jcarpanelli: https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1198#pullrequestreview-282705864
Note: `openzeppelin accounts` is only in 2.5.3 which is currently `@openzeppelin/cli@next` rather than `@latest`. So may need to wait until 2.5.3 is `@latest`
=> Update interacting.adoc to use `oz accounts`

packages/cli/src/commands/create.ts, packages/cli/src/commands/update.ts, packages/docs/modules/ROOT/pages/create-from-solidity.adoc, packages/docs/modules/ROOT/pages/first.adoc, packages/docs/modules/ROOT/pages/gsn-dapp.adoc, packages/docs/modules/ROOT/pages/linking.adoc, packages/docs/modules/ROOT/pages/public-deploy.adoc
Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1197.
=> Improve create and upgrade commands wording in prompts

packages/cli/src/commands/init.ts, packages/cli/src/models/compiler/solidity/SolidityContractsCompiler.ts, packages/cli/src/models/dependency/Dependency.ts, packages/cli/src/models/local/KitController.ts, packages/cli/src/prompts/method-params.ts, packages/cli/src/prompts/prompt.ts, packages/cli/src/prompts/validators.ts, packages/cli/test/mocks/mock-stdlib/contracts/GreeterImpl.sol, packages/cli/test/prompts/prompt.test.js
Fixes #1209. This PR fixes `oz call`, `oz send-tx`, `oz create` and `oz upgrade` interactive method and method arguments prompts when a contract has:
- A public mapping variable defined (and thus a getter function associated)
- A function that receives parameters without name.
In both cases, we are now showing the function definition without the variable name and a `#0`, `#1`, `#2`, ..., `#n` for each parameter without a name:
=> Avoid showing variable name on prompt message if not available

packages/docs/modules/ROOT/pages/public-deploy.adoc
gsn-dapp documentation: https://docs.openzeppelin.com/sdk/2.5/gsn-dapp#moving-to-testnet uses Rinkeby network, so added Rinkeby and Kovan (had issue with default gas limit for Goerli otherwise would have added as well)
=> Update public-deploy to include Rinkeby and Kovan

packages/cli/README.md
Fixed a link to documentation so it always defaults to current.
=> Fix Link to Documentation

packages/docs/modules/ROOT/pages/linking.adoc
The 2.4.0 version of @openzeppelin/upgrades no longer exists. Let's remove the version specification.
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @openzeppelin/upgrades@2.4.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
=> Fix npm install bug in manual

packages/cli/scripts/test.sh
Fixes issues reported by @abcoathup in #1241.
I'm not sure why the test script was only compiling in the CI before. I suspect it was because it doesn't work without `rm -rf`-ing the `build/contracts` directory first... And this wasn't necessary in the CI since it's a clean environment.
=> Force compilation to fix tests

packages/cli/src/telemetry/index.ts, packages/cli/src/telemetry/send-to-firebase.ts, packages/cli/test/telemetry.test.js, packages/docs/modules/ROOT/pages/faq.adoc
=> Upload user environment info in telemetry reports

packages/cli/package.json, packages/cli/src/commands/compile.ts, packages/cli/src/commands/init.ts, packages/cli/src/models/compiler/Compiler.ts, packages/cli/src/models/compiler/ProjectCompilerOptions.ts, packages/cli/src/models/compiler/Typechain.ts, packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts, packages/cli/src/models/files/ProjectFile.ts, packages/cli/src/prompts/typechain.ts, packages/cli/src/scripts/init.ts, packages/cli/src/scripts/interfaces.ts, packages/cli/test/commands/compile.test.js, packages/cli/test/commands/init.test.js, packages/cli/test/models/compiler/Compiler.test.js, yarn.lock
I added an optional typechain step to the compilation. If this feature is enabled, after compiling, every modified contract is run through typechain to generate typescript wrappers.
The user is queried whether to enable it on two commands, and _only if there is a `tsconfig.json`_ present (I'd like your thoughts on these!)
- Running `oz init`
- Running `oz compile` if there is no typechain info on the project.json file
The user is asked three questions:
- Whether to enable typechain
- Which target to use (web3, ethers, or truffle)
- The output dir
Typechain generation is quite fast, and the packages are rather small. I had initially loaded them lazily, but it ended up not making much of a difference including them in the package (not ethers though, since we don't officially support it). …
=> Typechain support

packages/docs/modules/ROOT/pages/gsn-dapp.adoc
`GSNRecipient` doesn't implement `_preRelayedCall` and `_postRelayedCall` so our `Counter` contract needs to otherwise it is abstract and can't be `oz create`d.
Add empty implementations of `_preRelayedCall` and `_postRelayedCall`
=> Update gsn-dapp.adoc for Contracts 2.4

packages/docs/modules/ROOT/pages/linking.adoc
Remove version `npm install @openzeppelin/upgrades@2.4.0` as `@openzeppelin/upgrades@2.4.0` doesn't exist and to use the latest version.
Raised in the forum: https://forum.openzeppelin.com/t/writing-upgradable-contracts/1820
=> Documentation: Update linking.adoc

packages/cli/src/models/compiler/solidity/SolidityContractsCompiler.ts
The build in https://github.com/OpenZeppelin/openzeppelin-sdk/commit/855c2ad6a0f43737dfeb6bf98a99c00448c88c31 failed due to corrupted JSON artifacts. This was caused by writing the artifacts of two separate contracts into the same file concurrently, which itself was caused by using the basename instead of the full path to the Solidity files.
=> Switch to identifying contracts by full path

packages/cli/src/prompts/prompt.ts
It doesn't make sense to have interactivity if stdin is not a terminal. We can check this using `tty.isatty`.
=> Disable interactivity if stdin is not a terminal

packages/docs/modules/ROOT/pages/gsn-dapp.adoc
Fix: `Line 20:7:  'deployedNetwork' is assigned a value but never used  no-unused-vars`
Remove `let deployedNetwork = undefined;` as not used.
Declared where used in an if: `const deployedNetwork = counterJSON.networks[context.networkId.toString()];`
=> Update gsn-dapp.adoc remove unused var

packages/cli/package.json, packages/cli/src/models/compiler/solidity/ResolverEngineGatherer.ts, packages/cli/src/models/compiler/solidity/SolidityProjectCompiler.ts, packages/cli/src/utils/solidity.ts, packages/cli/test/models/compiler/solidity/SolidityProjectCompiler.test.js, packages/lib/src/utils/Solidity.ts, yarn.lock
Increases performance of nothing-to-compile runs by using a custom fuzzy parser that only extracts imports from the text, instead of the full antlr4 parser.
Running both versions in the contracts repository, this yields a 40% speed increase when having nothing to compile.
This commit also lazy-loads truffle-flattener, which was causing significant delays to the CLI startup.
=> Use solidity fuzzy import parser

packages/cli/test/scripts/update.test.js
Some functions fail to execute during the default timeout of `2000` ms. This PR bumps timeout for them to `5000` ms.
```
1) update script
on dependency contract
updating on dependency
"before each" hook: setup for "should upgrade the version of all proxies":
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/circleci/openzeppelin/packages/cli/test/scripts/update.test.js)
"should not attempt to upgrade a minimal proxy":
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/c/Users/andre/Documents/projects/forum/openzeppelin-sdk/packages/cli/test/scripts/update.test.js)
```
=> Adds tests timeout to prevent CI from failing

yarn.lock
https://github.com/OpenZeppelin/docs-utils/commit/dc7ce3006b6065cc4edebe53896644da5bd7dbec fixes the bug that is causing the deploy preview to fail to build.
=> Bump OpenZeppelin/docs-utils to latest

packages/cli/package.json
The current version ranges allow an installation of `@openzeppelin/cli` to use a newer version of `@openzeppelin/upgrades`. Since we don't test these combinations, we feel it would be best to restrict the allowed version range.
=> Restrict version range of Upgrades allowed to be used with CLI

packages/docs/modules/ROOT/pages/faq.adoc
`openzeppelin compile --solc-version 5.X` should be `openzeppelin compile --solc-version 0.5.X`
Raised by a community member in Telegram.
I have specified the (current) latest version of solc 0.5.13.
=> Update faq.adoc for solc version in oz compile

packages/docs/modules/ROOT/pages/testing.adoc
Since we well want to revise this once `contract-loader` deprecates `Contracts.getFromLocal`, regular deploys are out and the new learn guides are published, I focused on replacing usage of truffle with `test-environment`.
I did improve a bit the last section, which was rather confusing (probably due to edits throughout the months?): it mentioned Truffle despite the contracts being web3 instances, and showcased the Crowdsale contracts, which handle inheritance and initialization in a very non-standard way. The new example is simpler and should make the issue clearer to the reader.
=> Remove Truffle references from advanced testing guide

packages/cli/package.json, packages/cli/src/models/config/ConfigManager.ts, yarn.lock
Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1227
The change itself is rather simple: the only thing I'm unsure is whether we should test this as a unit test, integration, or not at all.
That said, I want to discuss my findings while looking into this issue to provide some context that may help inform future decisions.
`lib` defines a `TxParams` object that is passed around when sending transactions and serves as a default for these. This object is populated by `ConfigManager` from the network configuration file, and before this PR, it only includes `from`. 
Because of this, I was surprised to see that the correct values for `gas` are nonetheless used in all transactions: it turns out `lib/utils/Transactions` handles a null value for `gas` by loading it from …
=> Load gas and gasPrice from networkConfig

packages/cli/src/interface/ValidationLogger.ts, packages/cli/test/interface/ValidationLogger.test.js, packages/lib/contracts/mocks/Invalid.sol, packages/lib/src/utils/ContractAST.ts, packages/lib/src/validations/VanillaContracts.ts, packages/lib/src/validations/index.ts, packages/lib/test/src/validations/Validations.test.js
Users should only install contracts from oz/contracts-eth-package, not oz/contracts. Warn about this when an import for the vanilla contracts package is found.
Fixes #1297
=> Warn when importing vanilla contracts package

packages/cli/contracts/mocks/ImplV1.sol, packages/cli/contracts/mocks/ImplV2.sol, packages/cli/package.json, packages/cli/src/models/network/TransactionController.ts, packages/cli/src/prompts/method-params.ts, packages/cli/src/prompts/prompt.ts, packages/cli/src/utils/input.ts, packages/cli/test/prompts/prompt.test.js, packages/cli/test/scripts/call.test.js, packages/cli/test/utils/input.test.js, packages/lib/src/artifacts/Contract.ts, packages/lib/src/utils/ABIs.ts, yarn.lock
Fixes #1330. Tuples can be entered as comma separated, or as comma separated enclosed in parenthesis.
=> Add tuple support in interactive prompts

packages/cli/src/interface/ValidationLogger.ts, packages/cli/test/interface/ValidationLogger.test.js
Fixes a bug introduced in https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1335 that causes **all** contracts to emit the following warning on `create`:
>- Contract <name> imports  from @openzeppelin/contracts. Use @openzeppelin/contracts-ethereum-package instead. See https://docs.openzeppelin.com/sdk/2.6/linking#linking-the-contracts-ethereum-package.
On `lib`, `importsVanillaContracts` return type is `string[] | undefined`. However, when `newValidationErrors` calls `lodash.difference`, a value of undefined is silently converted into the empty array:
```javascript
> difference(null, null)
[]
```
This is handled correctly in `validationPasses`, which uses `lodash.isEmpty`, but not on `ValidationLogger`, which just tests the result as a truthy value. Because **empty arrays are …
=> Fix false positive warning of library import

packages/cli/.eslintrc.js
As stated in [eslint config](https://eslint.org/docs/4.0.0/user-guide/configuring#configuring-rules) rules all the value can be either numeric or literal,  no booleans allowed.
```
"off" or 0 - turn the rule off
"warn" or 1 - turn the rule on as a warning (doesn't affect exit code)
"error" or 2 - turn the rule on as an error (exit code is 1 when triggered)
```
=> Fix eslint config for CLI

packages/cli/src/commands/create.ts, packages/cli/src/commands/push.ts, packages/cli/src/commands/update.ts
The force flag was being passed to push from both create and upgrade to force pushing the implementation contracts. This caused the contracts to be pushed even if they had validation errors. This commit removes that flag so the create or upgrade fails if there are any errors.
Fixes #1348
=> Stop interactive create or update on validation errors

packages/cli/src/models/config/NetworkConfig.ts, packages/cli/test/config/NetworkConfig.test.js
Add support for specifying an url entry with the full URL to the node. Also adds a new entry, path, that can be combined with host, protocol, and port, and makes port optional. Note that #1338 suggested accepting a path as part of the host, though this is not technically correct (hence the new path property).
Fixes #1338
=> Add url and path properties to network config

packages/cli/src/interface/ValidationLogger.ts, packages/cli/test/interface/ValidationLogger.test.js, packages/lib/contracts/mocks/Invalid.sol, packages/lib/src/artifacts/BuildArtifacts.ts, packages/lib/src/artifacts/Contract.ts, packages/lib/src/utils/ContractAST.ts, packages/lib/src/validations/Constructors.ts, packages/lib/src/validations/index.ts, packages/lib/test/mocks/mock-dependency/contracts/DependencyInvalid.sol, packages/lib/test/src/validations/Validations.test.js
=> Validate constructors in ancestor contracts

packages/cli/src/models/config/ConfigManager.ts, packages/cli/src/models/config/NetworkConfig.ts, packages/cli/src/models/config/TruffleConfig.ts, packages/cli/src/prompts/prompt.ts, packages/cli/test/prompts/prompt.test.js
=> Catch empty networks in network configuration files

packages/cli/src/models/dependency/Dependency.ts, packages/cli/src/models/files/ProjectFile.ts, packages/cli/test/models/ProjectFile.test.js
=> Store relative paths in project file

packages/cli/src/commands/deploy/action.ts, packages/cli/src/commands/deploy/spec.ts, packages/cli/src/models/config/ConfigManager.ts, packages/cli/src/register-command.ts, packages/cli/src/telemetry/index.ts, packages/cli/src/telemetry/send-to-firebase.ts, packages/cli/test/telemetry.test.js
The recent #1393 introduced some changes to `ZWeb3` initialization that made evident an issue with the deploy command: `ZWeb3` was being implicitly accessed too early by using methods in `ContractManager`. Too early means before the it had been initialized properly.
To solve this I added an optional post-processing step to the spec for every parameter, so once we have gathered all the required parameters, we use this step to initialize the config. Now that this is initialized at this time, I've also reverted the changes I had had to introduce to telemetry (to work around some of the config information not being available at the time the telemetry report was produced).
=> Fix regular deploy issues with ZWeb3 initialization

packages/cli/src/commands/deploy/spec.ts, packages/cli/src/register-command.ts, packages/cli/test/telemetry.test.js
Sorry, I didn't like the name `postprocess`
=> Rename postprocessing to after in commands spec

packages/cli/src/models/network/NetworkController.ts, packages/cli/test/scripts/push.test.js
After a push (which is run before every create or update) a message "All contracts have been deployed" is shown, which is confusing to the user, as the actual contract (ie the proxy) they wanted to create has *not* been deployed yet.
This commit changes the text to "All implementations have been deployed"
=> Change contracts to implementations in push msg

packages/cli/src/commands/push.ts, packages/cli/src/models/TestHelper.ts, packages/cli/src/models/network/NetworkController.ts, packages/cli/src/scripts/interfaces.ts, packages/cli/src/scripts/push.ts, packages/cli/src/telemetry/index.ts, packages/cli/test/scripts/push.test.js
Fixes #1250. Will push only request contract by `create` command. The same functionality theoretically can be implemented for `update` command as well but it will require quite a bit of rearchitecting due to `update` command accepting options like `all/alias/address` as well as these options being resolved down the call stack of the `update` command.
=> Push only required contract during create command

packages/lib/src/artifacts/ZWeb3.ts
Allow commands that do not require a web3 connection to create Contract instances.
Fixes #1436
This PR is **not** part of #1438, will need a separate merge once we release 2.7 final.
=> Fix check command

packages/lib/package.json
Porting https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1428 to `master`.
=> Move docgen to dev dependency

packages/cli/src/commands/verify/action.ts, packages/cli/src/commands/verify/spec.ts
Fixes an error introduced in #1443. Commit https://github.com/OpenZeppelin/openzeppelin-sdk/pull/1443/commits/575c4b06986937076f1d6d2e806b31a49343fd5b should have removed some lines but didn't.
Also removes an unused import.
The pull request is for CI. Will merge without review.
=> Fix error in verify spec

packages/cli/src/commands/verify/action.ts
`controller.isContractDeployed` checks if a contract is deployed as an _implementation_ for a proxy. If a contract isn't deployed, there is already an error produced by `checkLocalContractDeployed`. I added a different error which contains a warning about regular instances not being supported in verify yet.
=> Add nicer error message to catch verify of regular instances

.circleci/config.yml, examples/upgrades-library/package.json, package.json, packages/cli/package.json, packages/lib/package.json, tests/regular-deploys/.gitignore, tests/regular-deploys/.openzeppelin/project.json, tests/regular-deploys/contracts/Demo.sol, tests/regular-deploys/networks.js, tests/regular-deploys/package.json, tests/regular-deploys/test.js, yarn.lock
Adds an integration test that deploys a non-upgradeable instance using `deploy` and calls a function on it to verify the deploy went fine.
=> Integration test for regular deploys

tsconfig.json
Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1405.
The size of the compiled JavaScript was reduced by about 10%.
=> Change TypeScript compilation target to es2017

packages/cli/src/commands/deploy/action.ts, packages/cli/src/commands/verify/action.ts, packages/cli/src/commands/verify/spec.ts, packages/cli/src/telemetry/index.ts
Fixes #1464 
This bug was caused by a call to the Web3 network in `Telemetry.report`.
https://github.com/OpenZeppelin/openzeppelin-sdk/blob/08fdbaa4f9857f08dedeaa15900035156e1a60e0/packages/cli/src/telemetry/index.ts#L42
The reason this was there was that, in the new command framework, `Telemetry.report` is called before a command's action runs. Depending on the command spec, the network name may not be canonicalized yet. I've now changed the specs for `deploy` and `verify` to make sure the canonical name is already present once it reaches telemetry. (This was actually already done in `deploy`. I don't know why this code in telemetry had remained.)
We shouldn't rely on the spec to be coded this way though, and we need to introduce an abstraction here that would avoid the mistake of …
=> Fix network bug in init

packages/cli/src/commands/create.ts, packages/cli/src/commands/deploy/action.ts
We are deprecating `create` in favor of `deploy`.
=> Add deprecation warning to create

packages/cli/src/commands/deploy/spec.ts, packages/cli/src/commands/verify/action.ts, packages/cli/src/models/local/LocalController.ts, packages/cli/src/models/network/NetworkController.ts
Fixes #1470.
Fixes #1471.
Fixes #1468.
=> Fixes for 2.8

packages/cli/src/register-command.ts
=> Exit process after running a command

packages/cli/src/register-command.ts
We are using custom code for the help text (are we using commander for anything at all? :stuck_out_tongue:) and forgot to disable the default in the new command framework. It looked like this:
The same commands are already present later in the output.
=> Disable automatic help text in new command framework

tsconfig.json
Enabling declaration maps in TypeScript makes "jump to definition" go to the source code rather than the `d.ts` file.
=> Add declaration map configuration

packages/cli/src/commands/deploy/action.ts, packages/cli/src/scripts/create.ts
Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1410.
I'm not sure I love the way this looks, honestly. But we don't have another way to show this kind of notice right now. We can improve it in the future.
=> Add hint to use oz upgrade after upgradeable deployment

packages/cli/src/models/network/NetworkController.ts
Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1475
For cases when there is both upgradeable and regular instances of the same contract, this will print a warning in `verify` saying that verifying regular instances doesn't work yet.
=> Add extra warning in verify when a regular instance is found

README.md, examples/first-project/README.md, packages/cli/README.md, packages/cli/docs/modules/ROOT/pages/compiling.adoc, packages/cli/docs/modules/ROOT/pages/contracts-architecture.adoc, packages/cli/docs/modules/ROOT/pages/dependencies.adoc, packages/cli/docs/modules/ROOT/pages/deploying-with-create2.adoc, packages/cli/docs/modules/ROOT/pages/getting-started.adoc, packages/cli/docs/modules/ROOT/pages/index.adoc, packages/cli/docs/modules/ROOT/pages/publishing-ethereum-package.adoc, packages/cli/docs/modules/ROOT/pages/truffle.adoc, packages/cli/src/models/local/LocalController.ts, packages/lib/docs/modules/ROOT/pages/creating-upgradeable-from-solidity.adoc, packages/lib/docs/modules/ROOT/pages/proxies.adoc, packages/lib/docs/modules/ROOT/pages/writing-upgradeable.adoc
Our documentation and a message printed by the CLI said `oz create` where we should be recommending `oz deploy`. This changes that.
Should be cherry-picked into 2.8.
=> Change documentation and messages to use oz deploy

packages/cli/src/commands/create.ts, packages/cli/src/commands/push.ts, packages/cli/src/commands/update.ts
Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1508. Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1507.
This PR is going to `release/2.8` directly because the same fix is already implemented in the soon-to-be-merged #1497. In fact this change is mostly the same one found in https://github.com/OpenZeppelin/openzeppelin-sdk/commit/fc5926e96b9ba82c338c4b5fa8b3af2405866d59 of that PR.
There's a change that seems unrelated, making an argument into an array, but because `upgrade` can work on multiple contracts at once the way to obtain the contracts that need to be pushed gets us an array. I think in practice it will always be of length 1 but we can't be sure.
There are no tests in this PR because we currently have no tests for implicit commands like push is for …
=> Push contracts selectively during upgrades

lerna.json
This makes persistent the versioning settings that some of us have been using.
=> Configure lerna version bumping behavior

packages/cli/src/models/network/NetworkController.ts
Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1516.
At some point we introduced the "normalize contract alias" function and I think we replaced most uses of `.contract()` for it because it was almost the same, but it differs in an important detail when the contract is not local, which was causing this issue.
No regression tests because unfortunately we don't have an existing test setup for truffle deployed information.
=> Fix truffle deployed information for dependency contracts

packages/cli/src/commands/call.ts, packages/cli/src/commands/create.ts, packages/cli/src/commands/create2.ts, packages/cli/src/commands/send-tx.ts, packages/cli/src/commands/update.ts
Had to fix this, because even a year later I ran into it. Fast 5 minute fix to docs and messages.
Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1574. Fixes https://github.com/OpenZeppelin/openzeppelin-sdk/issues/783.
Happy to edit and include a note on ensuring no whitespace either. May be helpful to newer users.
=> fix for docs and help messages for args whitespace issue

packages/cli/package.json, packages/lib/package.json, packages/lib/src/helpers/advanceBlock.ts, yarn.lock
This PR bumps web3 version, therefore eliminating the need to compile with node-gyp.
=> Bump web3 version.
